Add files via upload

diff --git a/_rtd_functions b/_rtd_functions
--- a/_rtd_functions
+++ b/_rtd_functions
@@ -15,11 +15,11 @@
 
 function set_colors () {
 	# Set colors for prompting on screen.
-		YELLOW="\033[1;33m"
-		RED="\033[0;31m"
-		ENDCOLOR="\033[0m"
-		GREEN="\033[0;32m"
-		BLUE="\033[0;34m"
+	YELLOW="\033[1;33m"
+	RED="\033[0;31m"
+	ENDCOLOR="\033[0m"
+	GREEN="\033[0;32m"
+	BLUE="\033[0;34m"
 }
 
 
@@ -43,23 +43,23 @@ function set_install_command () {
 	# If you need to use this script in an rpm based system you could modify the install
 	# command here to dnf, yum, zypper... By default packages of patternd that do not
 	# match should be skipped. Use "export option" so child processes also see the variiables.
-				if [[ "$1" == "deb" ]]; then
-						# tell debian based installers (Ubuntu, Mint etc.) to be quiet.
-						export _INSTCMD="apt-get -y -qq --allow-change-held-packages --ignore-missing install"
-						export DEBIAN_FRONTEND=noninteractive
-						# Enable all repositories while disabling source repository list downloads in sources.list
-						sed -i -e "s/# deb http/deb http/g" /etc/apt/sources.list
-						sed -i -e "s/deb-src/# deb-src/g" /etc/apt/sources.list
+	if [[ "$1" == "deb" ]]; then
+	        # tell debian based installers (Ubuntu, Mint etc.) to be quiet.
+	        export _INSTCMD="apt-get -y -qq --allow-change-held-packages --ignore-missing install"
+	        export DEBIAN_FRONTEND=noninteractive
+	        # Enable all repositories while disabling source repository list downloads in sources.list
+	        sed -i -e "s/# deb http/deb http/g" /etc/apt/sources.list
+	        sed -i -e "s/deb-src/# deb-src/g" /etc/apt/sources.list
 
-				elif [[ "$1" == "darwin" ]]; then
-				        echo "Mac OSX is currently not supported..."
-				elif [[ "$1" == "rpm" ]]; then
-				        echo "RPM is not yet supported..."
-				elif [[ "$1" == "freebsd"* ]]; then
-				        echo "Free BSD is currently unsupported... "
-				else
-				       echo "This function talkes the parameters: deb, rpm, darwin, freebsd, please provide a parameter..."
-				fi
+	elif [[ "$1" == "darwin" ]]; then
+	        echo "Mac OSX is currently not supported..."
+	elif [[ "$1" == "rpm" ]]; then
+	        echo "RPM is not yet supported..."
+	elif [[ "$1" == "freebsd"* ]]; then
+	        echo "Free BSD is currently unsupported... "
+	else
+	       echo "This function talkes the parameters: deb, rpm, darwin, freebsd, please provide a parameter..."
+	fi
 }
 
 
@@ -69,19 +69,21 @@ function set_install_command () {
 
 
 function enable_firewall () {
-		# Enable firewall in Ubuntu systems
-		if hash ufw 2>/dev/null; then
-				echo -e $YELLOW "Configure Firewall:" $ENDCOLOR
-				ufw enable && ufw allow ssh
-		else
-				echo UFW not present on this system...
-		fi
+	# Enable firewall in Ubuntu systems
+	if hash ufw 2>/dev/null; then
+			echo -e $YELLOW "Configure Firewall:" $ENDCOLOR
+			ufw enable && ufw allow ssh
+	else
+			echo UFW not present on this system...
+	fi
 }
 
 
 
 
-
+# Function to ease and make consistent the downloading of the non repository packages and
+# install them. This function presently only works with apt. This should be expanded to include
+# RPM packages as well. 
 function dl ()
 {
 	if [ -z "$_ERRLOGFILE" ]; then $_ERRLOGFILE=$0.log ; else echo "Logfile is set to: '$_ERRLOGFILE'"; fi
@@ -98,73 +100,82 @@ function dl ()
 
 
 
-# Function to check and see if the system software managment is available
+# Function to check and see if the system software managment is available. In some cases 
+# the sofware managment system may be in use. Should this be the case, this function will
+# wait undill the system is free for use. 
 function SofwareManagmentAvailabilityCHK ()
 {
-echo -e $YELLOW"--- Checking if software maintenance system is available:" $ENDCOLOR
-i=0
-tput sc
-while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
-    case $(($i % 4)) in
-        0 ) j="-" ;;
-        1 ) j="\\" ;;
-        2 ) j="|" ;;
-        3 ) j="/" ;;
-    esac
-    tput rc
-    echo -en "\r[$j] Waiting for other software managers to finish..."
-    sleep 0.5
-    ((i=i+1))
-done
+        echo -e $YELLOW"--- Checking if software maintenance system is available:" $ENDCOLOR
+        i=0
+        tput sc
+        while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
+            case $(($i % 4)) in
+                0 ) j="-" ;;
+                1 ) j="\\" ;;
+                2 ) j="|" ;;
+                3 ) j="/" ;;
+            esac
+            tput rc
+            echo -en "\r[$j] Waiting for other software managers to finish..."
+            sleep 0.5
+            ((i=i+1))
+        done
 
-# Deprecated code below:
-# while [ -f /var/lib/dpkg/lock ] ;
-#		do
-#			echo The software managment system is locked...
-#			echo Waiting 10 seconds for software managment system to be ready:
-#			for i in {0..10}; do echo -ne "$i"'\r'; sleep 1; done; echo
-#			echo force unlocking package managment...
-#			rm -f  /var/lib/apt/lists/lock
-#			rm -f /var/lib/dpkg/lock
-#	done
+        # Deprecated code below:
+        # while [ -f /var/lib/dpkg/lock ] ;
+        #		do
+        #			echo The software managment system is locked...
+        #			echo Waiting 10 seconds for software managment system to be ready:
+        #			for i in {0..10}; do echo -ne "$i"'\r'; sleep 1; done; echo
+        #			echo force unlocking package managment...
+        #			rm -f  /var/lib/apt/lists/lock
+        #			rm -f /var/lib/dpkg/lock
+        #	done
 }
 
 
 
 
 
-# Function to simplify updating system completely...
+# Function to simplify updating system completely. At present this function simply 
+# uses apt but should be modified to update RPM if that is used on the system. 
 function up2date ()
 {
-				# Ensure that the expected variables are defined.
-				if [ -z "$_ERRLOGFILE" ]; then $_ERRLOGFILE=$0.log ; else echo "Logfile is set to: '$_ERRLOGFILE'"; fi
-				if [ -z "$_LOGFILE" ]; then $_LOGFILE=$0.log ; else echo "Logfile is set to: '$_LOGFILE'"; fi
+	# Ensure that the expected variables are defined.
+	if [ -z "$_ERRLOGFILE" ]; then $_ERRLOGFILE=$0.log ; else echo "Logfile is set to: '$_ERRLOGFILE'"; fi
+	if [ -z "$_LOGFILE" ]; then $_LOGFILE=$0.log ; else echo "Logfile is set to: '$_LOGFILE'"; fi
 
-				echo -e $YELLOW"---Running up2date function:" $ENDCOLOR
+	echo -e $YELLOW"---Running up2date function:" $ENDCOLOR
 
-				echo "--- Refreshing Software repositories; this may take a minute..."
-				apt-get update 1>>$_LOGFILE 2>>$_ERRLOGFILE
+	echo "--- Refreshing Software repositories; this may take a minute..."
+	apt-get update 1>>$_LOGFILE 2>>$_ERRLOGFILE
 
-				echo "--- Installing System Updates; this may take a minute..."
-				apt-get dist-upgrade -y -qq --allow-change-held-packages --ignore-missing 1>>$_LOGFILE 2>>$_ERRLOGFILE
+	echo "--- Installing System Updates; this may take a minute..."
+	apt-get dist-upgrade -y -qq --allow-change-held-packages --ignore-missing 1>>$_LOGFILE 2>>$_ERRLOGFILE
 
-				echo "--- Cleaning up unused software; this may take a minute..."
-				apt-get autoremove -y 1>>$_LOGFILE 2>>$_ERRLOGFILE
+	echo "--- Cleaning up unused software; this may take a minute..."
+	apt-get autoremove -y 1>>$_LOGFILE 2>>$_ERRLOGFILE
 }
 
 
 
 
 
-#Function to simplify the installation of software
+# Function to simplify the installation of software by including all display and 
+# installation logic for a given software provider. This should be expanded to include flatpack
+# snap and rpm for example. It should be the same consistent way no matter flavor of Linux. 
+# This function uses the "$_INSTCMD" to install software. "$_INSTCMD" is defined separatley and could 
+# be an RPM or deb string, or even snap or flatpack. A preference order between package system and
+# snap or flatpack use. 
 function InstallSoftwareFromRepo ()
 {
-		PAD="--------------------------------------------------"
-		LINE=$(printf "%s %s" "$@" "$PAD" | cut -c 1-${#PAD})
-		echo -ne "--- Installing "$LINE" ":" "\ & $_INSTCMD "$@" >>$0.log 2>&1 && printf "%b%-6s%b$GREEN [ OK ] $ENDCOLOR \n" ||printf "%b%-6s%b$RED [FAIL] $ENDCOLOR \n"
-		sleep 1
-		[ -e /var/lib/apt/lists/lock ] && rm -f  /var/lib/apt/lists/lock
-		[ -e /var/lib/dpkg/lock ] && rm -f /var/lib/dpkg/lock
+	PAD="--------------------------------------------------"
+	LINE=$(printf "%s %s" "$@" "$PAD" | cut -c 1-${#PAD})
+	echo -ne "--- Installing "$LINE" ":" "\ & $_INSTCMD "$@" >>$0.log 2>&1 && printf "%b%-6s%b$GREEN [ OK ] $ENDCOLOR \n" ||printf "%b%-6s%b$RED [FAIL] $ENDCOLOR \n"
+	# wait a small ammount of time to ensure that slow systems can catch up...
+	sleep 1
+	[ -e /var/lib/apt/lists/lock ] && rm -f  /var/lib/apt/lists/lock
+	[ -e /var/lib/dpkg/lock ] && rm -f /var/lib/dpkg/lock
 }
 
 
@@ -173,25 +184,26 @@ function InstallSoftwareFromRepo ()
 
 # Function to check that a piece of software is installed and if not install it.
 # Works for apt based systems currently. The function will take a parameter that is expected to
-# match the softwre command line name.
+# match the softwre command line name or rather the name of the package. This should get
+# updated to also check and install from snap and flatpack. 
 function check_dependencies ()
 {
-#---------------------------------------------------------------
-echo "Checking for script dependencies and install if not there..."
-#---------------------------------------------------------------
-    if hash $1 2>/dev/null; then
-        echo "I found that $1 is present on this system... thankyou for that! "
-    else
-        echo "You seem to have no $1... I will try to get it... "
-        apt install $1 -y
-            if [ $? != 0 ];
-            then
-                echo "That install didn't work out so well."
-                echo "Please manually try to add the software since I couldn't do it."
-                exit
+        #---------------------------------------------------------------
+        echo "Checking for script dependencies and install if not there..."
+        #---------------------------------------------------------------
+            if hash $1 2>/dev/null; then
+                echo "I found that $1 is present on this system... thankyou for that! "
+            else
+                echo "You seem to have no $1... I will try to get it... "
+                $_INSTCMD $1
+                    if [ $? != 0 ];
+                    then
+                        echo "That install didn't work out so well."
+                        echo "Please manually try to add the software since I couldn't do it."
+                        exit
+                    fi
+                echo "OK Done! Continuing..."
             fi
-        echo "OK Done! Continuing..."
-    fi
 }
 
 
