Add files via upload

diff --git a/_rtd_functions b/_rtd_functions
--- a/_rtd_functions
+++ b/_rtd_functions
@@ -8,20 +8,100 @@
 # function to simplify downloading debs from a website
 # First param is the URL, second is the name of the deb, to bypass version
 # naming issues, use wildcards like skype*.deb
+
+
+
+
+
+function set_colors () {
+	# Set colors for prompting on screen.
+		YELLOW="\033[1;33m"
+		RED="\033[0;31m"
+		ENDCOLOR="\033[0m"
+		GREEN="\033[0;32m"
+		BLUE="\033[0;34m"
+}
+
+
+
+
+
+
+function ensure_admin () {
+	# Ensure administrative privileges.
+	[ "$UID" -eq 0 ] || echo -e $YELLOW "This script needs administrative access..." $ENDCOLOR
+	[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
+}
+
+
+
+
+
+
+function set_install_command () {
+	# add global install command for portability and convenience
+	# If you need to use this script in an rpm based system you could modify the install
+	# command here to dnf, yum, zypper... By default packages of patternd that do not
+	# match should be skipped. Use "export option" so child processes also see the variiables.
+				if [[ "$1" == "deb" ]]; then
+									# tell debian based installers (Ubuntu, Mint etc.) to be quiet.
+									export _INSTCMD="apt-get -y -qq --allow-change-held-packages --ignore-missing install"
+									export DEBIAN_FRONTEND=noninteractive
+									# Enable all repositories while disabling source repository list downloads in sources.list
+										sed -i -e "s/# deb http/deb http/g" /etc/apt/sources.list
+										sed -i -e "s/deb-src/# deb-src/g" /etc/apt/sources.list
+
+				elif [[ "$1" == "darwin" ]]; then
+				        echo "Mac OSX is currently not supported..."
+				elif [[ "$1" == "rpm" ]]; then
+				        echo "RPM is not yet supported..."
+				elif [[ "$1" == "freebsd"* ]]; then
+				        echo "Free BSD is currently unsupported... "
+				else
+				       echo "This function talkes the parameters: deb, rpm, darwin, freebsd, please provide a parameter..."
+				fi
+}
+
+
+
+
+
+
+
+function enable_firewall () {
+					# Enable firewall in Ubuntu systems
+					if hash ufw 2>/dev/null; then
+						echo -e $YELLOW "Configure Firewall:" $ENDCOLOR
+						ufw enable && ufw allow ssh
+					else
+						echo UFW not present on this system...
+					fi
+}
+
+
+
+
+
 function dl ()
 {
-	echo geting package $2 ...
-	wget -P /var/apt/cache/archives/$1 >>$0.log 2>&1
-	echo Installing package $2 ...
-	dpkg -i /var/apt/cache/archives/$2 >>$0.log 2>&1
-	echo -- Installing dependencies for $2...
-	apt-get -f install -y --force-yes >>$0.log 2>&1
+	if [ -z "$_ERRLOGFILE" ]; then $_ERRLOGFILE=$0.log ; else echo "Logfile is set to: '$_ERRLOGFILE'"; fi
+	if [ -z "$_LOGFILE" ]; then $_LOGFILE=$0.log ; else echo "Logfile is set to: '$_LOGFILE'"; fi
+	echo    - geting package $2 ...
+	wget -P /var/apt/cache/archives/ $1 1>>$_LOGFILE 2>>$_ERRLOGFILE
+	echo "   - Installing package $2 ..."
+	dpkg -i /var/apt/cache/archives/$2 1>>$_LOGFILE 2>>$_ERRLOGFILE
+	echo "   - Installing dependencies for $2..."
+	apt-get -f install -y -qq --allow-change-held-packages 1>>$_LOGFILE 2>>$_ERRLOGFILE
 }
+
+
+
+
 
 # Function to check and see if the system software managment is available
 function SofwareManagmentAvailabilityCHK ()
 {
-echo Checking if software maintenance system is available...
+echo -e $YELLOW"--- Checking if software maintenance system is available:" $ENDCOLOR
 while [ -f /var/lib/dpkg/lock ] ;
 		do
 			echo The software managment system is locked...
@@ -30,36 +110,54 @@ while [ -f /var/lib/dpkg/lock ] ;
 			echo force unlocking package managment...
 			rm -f  /var/lib/apt/lists/lock
 			rm -f /var/lib/dpkg/lock
-			killall dpkg -y
-			dpkg-reconfigure -a
-			apt-get install -f
 	done
 }
+
+
+
+
 
 # Function to simplify updating system completely...
 function up2date ()
 {
-	echo Running up2date on behalf of $0
-	echo -- Refreshing Software repositories...
-	apt-get update  >>$0.log 2>&1
-	echo -- Installing System Updates...
-	apt-get dist-upgrade -y --force-yes >>$0.log 2>&1
-	echo -- Cleaning up unused software...
-	apt-get autoremove -y >>$0.log 2>&1
+				# Ensure that the expected variables are defined.
+				if [ -z "$_ERRLOGFILE" ]; then $_ERRLOGFILE=$0.log ; else echo "Logfile is set to: '$_ERRLOGFILE'"; fi
+				if [ -z "$_LOGFILE" ]; then $_LOGFILE=$0.log ; else echo "Logfile is set to: '$_LOGFILE'"; fi
+
+				echo -e $YELLOW"---Running up2date function:" $ENDCOLOR
+
+				echo "--- Refreshing Software repositories; this may take a minute..."
+				apt-get update 1>>$_LOGFILE 2>>$_ERRLOGFILE
+
+				echo "--- Installing System Updates; this may take a minute..."
+				apt-get dist-upgrade -y -qq --allow-change-held-packages --ignore-missing 1>>$_LOGFILE 2>>$_ERRLOGFILE
+
+				echo "--- Cleaning up unused software; this may take a minute..."
+				apt-get autoremove -y 1>>$_LOGFILE 2>>$_ERRLOGFILE
 }
+
+
+
+
 
 #Function to simplify the installation of software
 function InstallSoftwareFromRepo ()
 {
 		echo --- Installing "$@"
-		$_INSTCMD "$@" >>$0.log 2>&1 && echo -e "--- OK" || echo -e "--- Failed"
+		# echo --- Installing "$@" & $_INSTCMD "$@" >>$0.log 2>&1 && echo -e "$GREEN --- OK $ENDCOLOR" || echo -e "$RED --- FAIL $ENDCOLOR"
+		$_INSTCMD "$@" 1>>$_LOGFILE 2>>$_ERRLOGFILE && echo -e "$@ 	OK!" ||echo -e "$@ 	FAIL!"
 		sleep 2
-		rm -f  /var/lib/apt/lists/lock
-		rm -f /var/lib/dpkg/lock
+		[ -e /var/lib/apt/lists/lock ] && rm -f  /var/lib/apt/lists/lock
+		[ -e /var/lib/dpkg/lock ] && rm -f /var/lib/dpkg/lock
 }
+
+
+
+
+
 # Function to check that a piece of software is installed and if not install it.
 # Works for apt based systems.
-function check.dependencies ()
+function check_dependencies ()
 {
 #---------------------------------------------------------------
 echo "Checking for script dependencies and install if not there..."
@@ -78,3 +176,7 @@ echo "Checking for script dependencies and install if not there..."
         echo "OK Done! Continuing..."
     fi
 }
+
+
+# make prompt colors avaiable to any script that includes this function lbrary.
+set_colors
