Add files via upload

diff --git a/rtd-update-ubuntu b/rtd-update-ubuntu
--- a/rtd-update-ubuntu
+++ b/rtd-update-ubuntu
@@ -1,6 +1,6 @@
 #!/bin/bash
 PUBLICATION="RuntimeData Update Manager for Ubuntu"
-VERSION="1.10"
+VERSION="1.11"
 #
 #	RTD Ubuntu + derivatives software update script
 #   	Stephan, Sweden
@@ -23,19 +23,29 @@ VERSION="1.10"
 #
 # Set colors for prompting on screen.
 	YELLOW="\033[1;33m"
-	RED="\033[0;31m"
+	RED="\033[1;31m"
 	ENDCOLOR="\033[0m"
-	GREEN="\033[0;32m"
-	BLUE="\033[0;34m"
-
+	GREEN="\033[1;32m"
+	BLUE="\033[1;34m"
+	
 # Ensure administrative privileges.
-[ "$UID" -eq 0 ] || echo -e $YELLOW "This script needs administrative access..." $ENDCOLOR
+[ "$UID" -eq 0 ] && echo -e "Administrative Access OK" $ENDCOLOR || echo -e $YELLOW"This script needs administrative access..." $ENDCOLOR 
 [ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
 
-# get parameter if this script was called with one... 
-echo " ${0##*/} - $PUBLICATION: Version $VERSION"
+# Identify 
+clear	
+echo -e $GREEN"$PUBLICATION: Version $VERSION" $ENDCOLOR
+echo -e $GREEN"--------------------------------------------------------" $ENDCOLOR
+
+# get parameter if this script was called with one...
+#  ${0##*/} - 
+echo This tool makes it simple to update software from all channels 
+echo available on the system at once. It will update via the native
+echo -e "package manager as well as newer formats like $YELLOW"snap"$ENDCOLOR and $YELLOW"flatpak"$ENDCOLOR..."
+echo " " 
 echo This update script supports the following features:
-echo " "	
+echo " "
+echo " - Default option: Update via all configured channels."	
 echo " - Self-update: pass the parameter "update" to get the latest version. "
 echo " - Self-setup: pass the parameter "setup" to make sure that you are using "
 echo "   all software channels; apt (default), "snap" and "flatpack". "
@@ -53,32 +63,36 @@ if [ "$1" == "setup" ]; then
        	INSTRUCTION=setup_me
 fi
 
+
+
+# Enable RTD Functions...
+echo "Checking for RTD Functions..."
+FILE=/opt/rtd/scripts/_rtd_functions     
+if [ -f $FILE ]; then
+   echo -e $GREEN"RTD Functions are available: Loading them for use... " $ENDCOLOR
+   source $FILE
+else
+   echo "Cannot find RTD Functions... Attempting to get them online... "
+   wget -q --show-progress https://github.com/vonschutter/RTD-Build/raw/master/"$FILE" -P /opt/rtd/scripts
+   if [ -f $FILE ]; then
+   	echo -e $GREEN"RTD Functions are available: Loading them for use... " $ENDCOLOR
+   	source $FILE
+   else
+   	echo -e $RED"RTD Functions could NOT be loaded; You must use the native options to instal software... "$ENDCOLOR
+   	exit 
+   fi
+fi
+
+
+
+
+
 ###########################################################################
 ##                                                                       ##
 ##                         Functions                                     ##
 ##                                                                       ##
 ###########################################################################
 #
-
-function check.dependencies ()
-{
-echo -e $YELLOW $0
-echo "Checking for script dependencies and install if not there..."
-    if hash $1 2>/dev/null; then
-        echo "I found that $1 is present on this system... thankyou for that! "
-    else
-        echo -e $RED "You seem to have no $1... I will try to get it... "
-        apt install $1 -y
-            if [ $? != 0 ];
-            then
-                echo "That install didn't work out so well."
-                echo "Please manually try to add the software since I couldn't do it."
-                exit
-            fi
-        echo -e $ENDCOLOR
-        echo "OK Done! Continuing..."
-    fi
-}
 
 function deb_software_task ()
 {
@@ -118,33 +132,9 @@ function config_me ()
 
 function setup_me ()
 {
-	check.dependencies flatpak
-	check.dependencies gnome-software-plugin-flatpak
+	check_dependencies flatpak
 	flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
-	check.dependencies snap
-}
-
-# Function to check and see if the system software managment is available. In some cases 
-# the sofware managment system may be in use. Should this be the case, this function will
-# wait undill the system is free for use. 
-function SofwareManagmentAvailabilityCHK ()
-{
-        echo -e $YELLOW"--- Checking if software maintenance system is available:" $ENDCOLOR
-        i=0
-        tput sc
-        while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
-            case $(($i % 4)) in
-                0 ) j="-" ;;
-                1 ) j="\\" ;;
-                2 ) j="|" ;;
-                3 ) j="/" ;;
-            esac
-            tput rc
-            echo -en "\r[$j] Waiting for other software managers to finish..."
-            echo " "
-            sleep 0.5
-            ((i=i+1))
-        done
+	check_dependencies  snap
 }
 
 ###########################################################################
@@ -164,7 +154,7 @@ else
 	log_item No instructions passed to $0... Continuing with default behavior. 
 fi
 
-echo -e $YELLOW "Updating installed software..." $ENDCOLOR
+echo -e $YELLOW"Updating installed software..." $ENDCOLOR
 # Updating software managed by distribution speciffic software manager...
 	deb_software_task apt-get update
 	UPGRADABLE=$(LANG=C apt-get upgrade -s |grep -P '^\d+ upgraded'|cut -d" " -f1)
@@ -172,9 +162,7 @@ echo -e $YELLOW "Updating installed software..." $ENDCOLOR
 		echo "--- $UPGRADABLE packages that need updates; Skipping update task... " 
 	else
 		echo $UPGRADABLE packages that need updates 
-		SofwareManagmentAvailabilityCHK 
 		deb_software_task apt-get upgrade -y
-		SofwareManagmentAvailabilityCHK 
 		deb_software_task apt-get autoremove -y
 	fi
 # updating snaps if snap is present on the system... 
