reset

diff --git a/System_Setup/_rtd_functions b/System_Setup/_rtd_functions
--- a/System_Setup/_rtd_functions
+++ b/System_Setup/_rtd_functions
@@ -1,32 +1,32 @@
 #!/bin/bash
 #
-#::				R T D   F u n c t i o n   L i b r a r y  
+#::				R T D   F u n c t i o n   L i b r a r y
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::	Author(s):   	SLS, KLS, NB.  Buffalo Center, IA & Avarua, Cook Islands
 #:: 	Version:	1.02
 #::
 #::
-#::	Purpose:	To collect and enable the use of code snipplets in other scripts. 
-#::			To document these thuroughly so that they may be usefull for learning BASH. 
+#::	Purpose:	To collect and enable the use of code snipplets in other scripts.
+#::			To document these thuroughly so that they may be usefull for learning BASH.
 #::     Usage: 		call this file using the "source" statment in bash.
-#:: 
+#::
 #::     This script is shared in the hopes that
 #::     someone will find it usefull.
 #::
 #::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-#	
+#
 #	Functions defined in this library:
 #
 #	Function Name: 				Description:
 #	----------------------------------------------------------------------------------------------------------------
-#	check_dependencies			: Checks that software requirements are met so scripts do not fail 
+#	check_dependencies			: Checks that software requirements are met so scripts do not fail
 #	debug_list_loaded_functions		: Lists all loaded RTD functions in the environment
 #	dl					: Downloads and installs a package from the internet (a bit insecure)
 #	enable_firewall				: Will turn on UFW and add the Allow SSH rule
-#	ensure_admin				: Elevates priveledges to admin "root" for the whole script (asks for password)  
+#	ensure_admin				: Elevates priveledges to admin "root" for the whole script (asks for password)
 #	InstallSoftwareFromRepo			: Installs a package from a repository (supports SUSE, Fedora, Cent OS, Ubuntu Deian etc.)
 #	is_software_package_available		: Checks to see if a software package is availabel in a repository (RPM and DEB)
 #	is_software_package_installed		: Checks to see if a software package allready is installed
@@ -37,9 +37,9 @@
 #	system_update				: Newer more universal software update function
 #	up2date					: Older universal software update function
 #	rtd_setup_choices_term_fallback		: For server setup, displays a menu where you may chose CLI productivity software (vim, alpine, byobu etc.).
-#	
-#	
-#	
+#
+#
+#
 
 ###########################################################################
 ##                                                                       ##
@@ -62,7 +62,7 @@ source /opt/rtd/scripts/_branding
 
 
 # Set colors for prompting on screen in human readable variables. These will be set globally
-# and can be can be used by in echo statements to modify the color of the message. 
+# and can be can be used by in echo statements to modify the color of the message.
 # Examples:  $YELLOW, $RED, $ENDCOLOR (reset), $GREEN, $BLUE
 set_colors () {
 	YELLOW="\033[1;33m"
@@ -113,8 +113,8 @@ set_colors () {
 
 
 
-# Function to ensure administrative privileges such that system wide settings 
-# or configuration may be done. This function will make the script call itself 
+# Function to ensure administrative privileges such that system wide settings
+# or configuration may be done. This function will make the script call itself
 # with sudo if the user ID is not 0 e.g. root.
 ensure_admin () {
 	[ "$UID" -eq 0 ] || echo -e $YELLOW "This script needs administrative access..." $ENDCOLOR
@@ -134,7 +134,7 @@ set_install_command () {
         if [[ "$OSTYPE" == "linux-gnu" ]]; then
 	        if hash pkcon 2>/dev/null; then
 			# If package kit is available then prefer this
-			echo -e $YELLOW "Setting install options for Package Kit" $ENDCOLOR	 
+			echo -e $YELLOW "Setting install options for Package Kit" $ENDCOLOR
 			export _INSTCMD="pkcon -y  install"
 		elif hash yum 2>/dev/null; then
 			# If package kit is not available try yum (RedHat, Cent OS, Fedora)
@@ -142,7 +142,7 @@ set_install_command () {
 	        	export _INSTCMD="yum -y  install"
 	        elif hash apt 2>/dev/null; then
 			# If package kit is not available try apt (Debian, Ubuntu, and all derivatives)
-		        echo -e $YELLOW "Setting install options for DEB" $ENDCOLOR	        
+		        echo -e $YELLOW "Setting install options for DEB" $ENDCOLOR
 	                export _INSTCMD="apt-get -y -qq --allow-change-held-packages --ignore-missing install"
 	                export DEBIAN_FRONTEND=noninteractive
 	        elif hash zypper 2>/dev/null; then
@@ -171,8 +171,8 @@ set_install_command () {
 
 
 # Function to enable system firewall and add a given rule. This simple function
-# enables Uncomplicated Fire Wall (UFW) and adds a rule to allow SSH to 
-# pass. 
+# enables Uncomplicated Fire Wall (UFW) and adds a rule to allow SSH to
+# pass.
 enable_firewall () {
 	if hash ufw 2>/dev/null; then
 			echo -e $YELLOW "Configure Firewall:" $ENDCOLOR
@@ -188,7 +188,7 @@ enable_firewall () {
 
 # Function to ease and make consistent the downloading of the non repository packages and
 # install them. This function presently only works with apt. This should be expanded to include
-# RPM packages as well. 
+# RPM packages as well.
 # First parameter is the URL, second is the name of the deb, to bypass version
 # naming issues, use wildcards like skype*.deb
 dl ()
@@ -201,16 +201,16 @@ dl ()
 
 	echo  "    - getting package $download_url ..."
 	if hash wget >/dev/null ; then
-		fetch_file 
-	else 
+		fetch_file
+	else
 		check_dependencies wget
-		fetch_file 
+		fetch_file
 	fi
 
 	echo "    - Installing package $download_file ..."
 	if hash pkcon >/dev/null ; then
 		pkcon install-local -y /opt/rtd/cache/$download_file 1>>$_LOGFILE 2>>$_ERRLOGFILE
-	else 
+	else
 		check_dependencies packagekit-tools
 		pkcon install-local -y /opt/rtd/cache/$download_file 1>>$_LOGFILE 2>>$_ERRLOGFILE
 	fi
@@ -219,9 +219,9 @@ dl ()
 
 
 
-# Function to check and see if the system software managment is available. In some cases 
+# Function to check and see if the system software managment is available. In some cases
 # the sofware managment system may be in use. Should this be the case, this function will
-# wait undill the system is free for use. 
+# wait undill the system is free for use.
 # TODO: Add support for fedora, Centos, SuSE.
 SofwareManagmentAvailabilityCHK ()
 {
@@ -247,12 +247,12 @@ SofwareManagmentAvailabilityCHK ()
 
 
 
-# Function to reset temporary configurations to their original setings from the 
-# distributor. To configure and/or automatically install Linux systems RTD OEM 
-# load process must make some changes to the system in question that are not 
-# good security practice or that may be disruptive during normal operations. 
-# These setings are not limited to bu include "auto login", "auto sudo" and 
-# "auto running scripts"... 
+# Function to reset temporary configurations to their original setings from the
+# distributor. To configure and/or automatically install Linux systems RTD OEM
+# load process must make some changes to the system in question that are not
+# good security practice or that may be disruptive during normal operations.
+# These setings are not limited to bu include "auto login", "auto sudo" and
+# "auto running scripts"...
 rtd_oem_reset_default_environment_config () {
 
 	# Disable the automatically trying to install OEM software
@@ -263,11 +263,11 @@ rtd_oem_reset_default_environment_config () {
 
 
 
-# Function that, when called, will wait for an active internet connection 
-# to be available before before continuing. Most softwrare install activities 
-# need an active internet connection to be able to install and update software. 
-# Naturally, some in house loads use local mirrors, but if you can see the 
-# internet, you would have access to your own ropositories as well... 
+# Function that, when called, will wait for an active internet connection
+# to be available before before continuing. Most softwrare install activities
+# need an active internet connection to be able to install and update software.
+# Naturally, some in house loads use local mirrors, but if you can see the
+# internet, you would have access to your own ropositories as well...
 rtd_wait_for_internet_availability () {
 	echo "Waiting for internet access..."
 	echo "NOTE: Free access to the internet is required to continue."
@@ -280,13 +280,13 @@ rtd_wait_for_internet_availability () {
 
 
 
-# Function to simplify updating system completely. At present this function sets the 
+# Function to simplify updating system completely. At present this function sets the
 # highest preference to use "pkcon", the command line interface of "Package Kit" since
 # this is the most consistent across different distrbutions. It may even work on BSD.
-# Only if "pkcon" is not available, will the function use the identified distro native 
-# software manager: apt, yum, zypper etc. This is to maintain stability since a distro may 
-# alias another distributions command (like SuSE does with apt) to be helpfull. 
-# This is one of the first update functions written and is kept for compatibility.  
+# Only if "pkcon" is not available, will the function use the identified distro native
+# software manager: apt, yum, zypper etc. This is to maintain stability since a distro may
+# alias another distributions command (like SuSE does with apt) to be helpfull.
+# This is one of the first update functions written and is kept for compatibility.
 up2date ()
 {
 	echo -e $YELLOW"--- Running up2date function:" $ENDCOLOR
@@ -294,15 +294,15 @@ up2date ()
         if [ -z "$_LOGFILE" ]; then $_LOGFILE=$0.log ; else echo "     Logfile is set to: '$_LOGFILE'"; fi
 
         if hash pkcon 2>/dev/null; then
-		pkcon update -y 1>>$_LOGFILE 2>>$_ERRLOGFILE 
+		pkcon update -y 1>>$_LOGFILE 2>>$_ERRLOGFILE
 	elif hash yum 2>/dev/null; then
-	        yum update -y 1>>$_LOGFILE 2>>$_ERRLOGFILE 
+	        yum update -y 1>>$_LOGFILE 2>>$_ERRLOGFILE
         elif hash apt 2>/dev/null; then
 	        apt-get update 1>>$_LOGFILE 2>>$_ERRLOGFILE
 	        apt-get dist-upgrade -y -qq --allow-change-held-packages --ignore-missing 1>>$_LOGFILE 2>>$_ERRLOGFILE
-	        apt-get autoremove -y 1>>$_LOGFILE 2>>$_ERRLOGFILE 
+	        apt-get autoremove -y 1>>$_LOGFILE 2>>$_ERRLOGFILE
         elif hash zypper 2>/dev/null; then
-                return zypper up 1>>$_LOGFILE 2>>$_ERRLOGFILE 
+                return zypper up 1>>$_LOGFILE 2>>$_ERRLOGFILE
 	else
 	        return 3
         fi
@@ -316,13 +316,13 @@ up2date ()
 # if the package manager is deb, zypper or rpm, and then take one parameter passed
 # and evauate if a software package by that name is installed. This function
 # will return a "0" or "1" return based on the package managers return code.
-# Call this function by: 
-# is_software_package_installed "package name" 
-#                 or 
+# Call this function by:
+# is_software_package_installed "package name"
+#                 or
 # is_software_package_installed "$1" if calling this function from a script
 # or another function receiving a parameter.
 #
-is_software_package_installed () 
+is_software_package_installed ()
 {
         if hash yum 2>/dev/null; then
 	        rpm -q "$1" > /dev/null 2>&1 && return 0 || return 1
@@ -336,19 +336,19 @@ is_software_package_installed ()
 }
 
 
-	
 
-# Function to chek if a package is available in whetever repository, and 
-# if there return a "0" and if not return a "1" or a "3" if there is no recognizable 
-# package manager found. the function expects the name of the package 
-# to be a parameter passed to this fuction. Call this function by: 
-# is_software_package_available "package name" 
-#                 or 
+
+# Function to chek if a package is available in whetever repository, and
+# if there return a "0" and if not return a "1" or a "3" if there is no recognizable
+# package manager found. the function expects the name of the package
+# to be a parameter passed to this fuction. Call this function by:
+# is_software_package_available "package name"
+#                 or
 # is_software_package_available "$1" if calling this function from a script
 # or another function receiving a parameter.
 #
 # Supported base distributions: Fedora . SuSE . Debian
-is_software_package_available () 
+is_software_package_available ()
 {
         if hash yum 2>/dev/null; then
 	        yum list available "$1" &> /dev/null && return 0 || return 1
@@ -365,17 +365,17 @@ is_software_package_available ()
 
 
 
-# Function to simplify the installation of software by including all display and 
+# Function to simplify the installation of software by including all display and
 # installation logic for a given software provider. This should be expanded to include flatpack
-# snap for example. It should be the same consistent way no matter flavor of Linux. 
-# This function uses the "$_INSTCMD" to install software. "$_INSTCMD" is defined separatley 
-# in the "set_install_command" function (a dependency to this function) and could 
+# snap for example. It should be the same consistent way no matter flavor of Linux.
+# This function uses the "$_INSTCMD" to install software. "$_INSTCMD" is defined separatley
+# in the "set_install_command" function (a dependency to this function) and could
 # be an RPM or deb string, or even snap or flatpack. A preference order between package system and
-# snap or flatpack use. 
+# snap or flatpack use.
 InstallSoftwareFromRepo ()
 {
-	# Check that function dependencies are available. 
-	# for _i in set_install_command is_software_package_installed is_software_package_available 
+	# Check that function dependencies are available.
+	# for _i in set_install_command is_software_package_installed is_software_package_available
 	# do
 	# 	if hash $_i 2>/dev/null; then
 	# 		return 0
@@ -385,7 +385,7 @@ InstallSoftwareFromRepo ()
 	# 		exit
 	# 	fi
 	# done
-	# Ensure that the CLI command is determined for this system. 
+	# Ensure that the CLI command is determined for this system.
 	set_install_command >>/dev/null 2>&1
 
 	# make some decent display terminal Graphics...
@@ -396,10 +396,10 @@ InstallSoftwareFromRepo ()
         if ! is_software_package_installed "$1"; then
         	if is_software_package_available "$1"; then
 			echo -ne "$PRE"\ & $_INSTCMD "$1" >>$0.log 2>&1 && printf "%b%-6s%b [ \xE2\x9C\x94 ] $GREEN OK!$ENDCOLOR \n" ||printf "%b%-6s%b [ ! ] $RED FAILED $ENDCOLOR \n"
-			if [ $? != 0 ]; 
-			then 
+			if [ $? != 0 ];
+			then
 				return 1 & exit 1
-			fi 
+			fi
 		else
 			echo -ne "$PRE"\ && printf "%b%-6s%b [ \xE2\x9C\x94 ] $YELLOW NOT AVAILABLE... $ENDCOLOR \n"
                 fi
@@ -414,7 +414,7 @@ InstallSoftwareFromRepo ()
 # Function to check that a piece of software is installed and if not install it.
 # Works for apt based systems currently. The function will take a parameter that is expected to
 # match the softwre command line name or rather the name of the package. This should get
-# updated to also check and install from snap and flatpack. 
+# updated to also check and install from snap and flatpack.
 check_dependencies () {
         #---------------------------------------------------------------
         echo "Checking for script dependencies and install if not there..."
@@ -426,7 +426,7 @@ check_dependencies () {
                 InstallSoftwareFromRepo $1
                     if [ $? != 0 ];
                     then
-                        echo -e $RED "That install didn't work out so well." 
+                        echo -e $RED "That install didn't work out so well."
                         echo -e "Please manually try to add the software since I couldn't do it." $ENDCOLOR
                         exit
                     fi
@@ -437,11 +437,11 @@ check_dependencies () {
 
 
 
-# Function to update the Linux based system. This function is universal for all 
+# Function to update the Linux based system. This function is universal for all
 # distributions that have package kit available. It works in the same manner on
-# RedHat/Fedora, Debian/Ubuntu and all their derivatives. When invoked as a 
-# part in a script, it is wist to ensure that the package kit is available 
-# by using the "check_dependencies" function to ensure that the software is available. 
+# RedHat/Fedora, Debian/Ubuntu and all their derivatives. When invoked as a
+# part in a script, it is wist to ensure that the package kit is available
+# by using the "check_dependencies" function to ensure that the software is available.
 system_update () {
     if hash pkcon 2>/dev/null; then
     	pkcon refresh
@@ -474,15 +474,15 @@ function notice_rtd_loaded ()
 
 
 # Function to display legacy installation options. This will install software that is usefull
-# on a really old system, or a remote system only accessible via SSH. This may be a good 
-# usecase if oyu happen to be in an opressed geographic locaiton where your only option is 
+# on a really old system, or a remote system only accessible via SSH. This may be a good
+# usecase if oyu happen to be in an opressed geographic locaiton where your only option is
 # to ssh to a remote server and access email and web that way. Perfomance in these cases
 # may be very poor over the internet (as for example with the great firewall of China). In
-# Such a case it would be usefull to have the good old CLI software! :) 
+# Such a case it would be usefull to have the good old CLI software! :)
 function rtd_setup_choices_term_fallback () {
 	# List Options to be available for choice in the RTD System Configurator...
 	cmd=(whiptail --backtitle "RTD OEM System Builder Configuraton Menu" --title "Terminal Software Options Menu" --separate-output --checklist "We did not find a graphical interface. No matter, you can be productive in the cli environment. Please Select Software and Configuration below:" 22 85 16 )
-	options=(1 "Base RTD OEM Software" on    
+	options=(1 "Base RTD OEM Software" on
 		 2 "Alpine email client" on
 		 3 "Vim text editor" on
 		 4 "Finch multi protocol chat" on
@@ -514,13 +514,13 @@ function rtd_setup_choices_term_fallback () {
 				InstallSoftwareFromRepo alpine
 				;;
 				3)
-				InstallSoftwareFromRepo vim	
+				InstallSoftwareFromRepo vim
 				;;
 				4)
 				InstallSoftwareFromRepo finch
 				;;
 				5)
-				InstallSoftwareFromRepo	wordgrinder		
+				InstallSoftwareFromRepo	wordgrinder
 				;;
 				6)
 				InstallSoftwareFromRepo sc
@@ -572,19 +572,16 @@ function rtd_setup_choices_term_fallback () {
 function debug_list_loaded_functions ()
 {
 	echo -e $BLUE "RTD Functions Loaded:"
-	declare -F | awk '{print $NF}' | sort | egrep -v "^_" 
+	declare -F | awk '{print $NF}' | sort | egrep -v "^_"
 }
 
-
+echo ${FUNCNAME[*]}
 
 # make prompt colors avaiable to any script that includes this function lbrary.
 set_colors
-notice_rtd_loaded 
+notice_rtd_loaded
 
 
 if [[ "$1" = "--list" ]]; then
 	debug_list_loaded_functions
 fi
-
-
-
