...

diff --git a/System_Setup/_rtd_library b/System_Setup/_rtd_library
--- a/System_Setup/_rtd_library
+++ b/System_Setup/_rtd_library
@@ -488,14 +488,77 @@ display_spinner ()
 #
 #
 # End of documentation
-	i=1
-	sp="/-\|"
-	echo -n ' '
-	while true
-	do
-		printf "\b[${sp:i++%${#sp}:1}]\b\b"
-		sleep 1
-	done
+
+		function _spinner() {
+		# $1 start/stop
+		#
+		# on start: $2 display message
+		# on stop : $2 process exit status
+		#           $3 spinner function pid (supplied from stop_spinner)
+
+		local on_success="DONE"
+		local on_fail="FAIL"
+		local white="\e[1;37m"
+		local green="\e[1;32m"
+		local red="\e[1;31m"
+		local nc="\e[0m"
+
+		case $1 in
+			start)
+			# calculate the column where spinner and status msg will be displayed
+			let column=$(tput cols)-${#2}-8
+			# display message and position the cursor in $column column
+			echo -ne ${2}
+			printf "%${column}s"
+
+			# start spinner
+			i=1
+			sp='\|/-'
+			delay=${SPINNER_DELAY:-0.15}
+
+			while :
+			do
+				printf "\b[${sp:i++%${#sp}:1}]\b\b"
+				sleep $delay
+			done
+			;;
+			stop)
+			if [[ -z ${3} ]]; then
+				echo "spinner is not running.."
+				exit 1
+			fi
+
+			kill $3 > /dev/null 2>&1
+
+			# inform the user uppon success or failure
+			echo -en "\b["
+			if [[ $2 -eq 0 ]]; then
+				echo -en "${green}${on_success}${nc}"
+			else
+				echo -en "${red}${on_fail}${nc}"
+			fi
+			echo -e "]"
+			;;
+			*)
+			echo "invalid argument, try {start/stop}"
+			exit 1
+			;;
+		esac
+		}
+
+		function start_spinner {
+		# $1 : msg to display
+		_spinner "start" "${1}" &
+		# set global spinner pid
+		_sp_pid=$!
+		disown
+		}
+
+		function stop_spinner {
+		# $1 : command exit status
+		_spinner "stop" $1 $_sp_pid
+		unset _sp_pid
+		}
 
 }
 
@@ -3266,7 +3329,7 @@ add_software_task ()
 
 	PAD="------------------------------------------"
 	LINE=$(printf "%s %s" "$@" "$PAD" | cut -c 1-${#PAD})
-	echo -ne "Installing "$LINE"":""\ display_spinner & $@ &>/dev/null && printf "%b%-6s%b [ \xE2\x9C\x94 ] $GREEN OK!$ENDCOLOR   \n" ||printf "%b%-6s%b [ ! ] $RED FAILED $ENDCOLOR  \n"
+	echo -ne "Installing ${LINE/recipe_/}: "  & $@ &>/dev/null && printf "%b%-6s%b [ \xE2\x9C\x94 ] $GREEN OK!$ENDCOLOR   \n" ||printf "%b%-6s%b [ ! ] $RED FAILED $ENDCOLOR  \n"
 }
 
 
