Week 50 updates
compressed script lines, rtd functions legacy, added rtd_library

diff --git a/System_Setup/_rtd_library b/System_Setup/_rtd_library
--- a/System_Setup/_rtd_library
+++ b/System_Setup/_rtd_library
@@ -84,10 +84,19 @@ _STATUSLOG=$_RTDLOGSD/$( basename $0)-status.log
 
 
 
+
+set_colors () 
+{
 # Set colors for prompting on screen in human readable variables. These will be set globally
 # and can be can be used by in echo statements to modify the color of the message.
 # Examples:  $YELLOW, $RED, $ENDCOLOR (reset), $GREEN, $BLUE
-set_colors () {
+# Usage: 
+#	Simply call this function by stating its name:
+# 	set_colors
+# 	
+# The function will not return any sucess or failure codes. It will do its best and exit.
+# End of documentation
+
 	YELLOW="\033[1;33m"
 	RED="\033[0;31m"
 	ENDCOLOR="\033[0m"
@@ -164,19 +173,21 @@ set_colors () {
 
 
 
-ensure_admin () {
+ensure_admin () 
+{
 # Function to ensure administrative privileges such that system wide settings
 # or configuration may be done. This function will make the script call itself
 # with sudo if the user ID is not 0 e.g. root.
 # End of documentation
-	[ "$UID" -eq 0 ] || echo -e $YELLOW "This script needs administrative access..." $ENDCOLOR
-	[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
+	[[ "$UID" -eq 0 ]] || echo -e $YELLOW "This script needs administrative access..." $ENDCOLOR
+	[[ "$UID" -eq 0 ]] || sudo bash "$0" "$*"
 }
 
 
 
 
-rtd_oem_kde_set_wallpaper(){
+rtd_oem_kde_set_wallpaper()
+{
 # rtd_oem_kde_set_wallpaper
 # Function to set KDE Plasma wallpaper from a script. this function expects one variable 
 # indication what file to set as background. You must provide the full path to the file. 
@@ -218,7 +229,77 @@ rtd_oem_kde_set_wallpaper(){
 
 
 
-set_install_command () {
+rtd_oem_remove_non_western_latin_fonts () 
+{
+# rtd_oem_remove_non_western_latin_fonts: a simple function to remove known
+# non-western (latin) fonts from a distribution. Notably, Ubuntu provides too many fonts
+# of all kinds by default, even if the user will never need the fonts. However, the fonts
+# may cause unexpected font tool behavior and crashes, due to the large number of fonts 
+# and their features. It is there fore a good Idea to remove these fonts if they are not needed.
+# Usage: 
+#	Simply call this function by stating its name:
+# 	rtd_oem_remove_non_western_latin_fonts
+# 	
+# The function will not return any sucess or failure codes. It will do its best and exit.
+# End of documentation
+
+	font_list="fonts-kacst fonts-kacst-one fonts-khmeros-core fonts-lklug-sinhala fonts-lohit-guru fonts-guru fonts-nanum fonts-noto-cjk fonts-takao-pgothic fonts-tibetan-machine fonts-guru-extra fonts-lao fonts-sil-padauk fonts-sil-abyssinica fonts-tlwg-* fonts-beng fonts-beng-extra fonts-deva fonts-deva-extra fonts-gubbi fonts-gujr fonts-gujr-extra fonts-kalapi fonts-knda fonts-lohit-* fonts-noto-* fonts-orya* fonts-pagul fonts-sahadeva fonts-samyak-* fonts-sarai fonts-smc fonts-smc-* fonts-taml fonts-telu fonts-telu-extra"
+	echo "Attempting to remove non-western fonts..."
+	for i in $font_list ; do 
+		rtd_oem_remove_software $i &>/dev/null
+	done
+}
+
+
+
+rtd_oem_remove_software () 
+{
+# rtd_oem_remove_software
+# The OEM remove software function will attempt to remove whatever package name given
+# as an argument using whatever package system found on the system. This is provided 
+# for portability and convenience. Currently, this functions will attempt to use
+# pkcon (prefferred as it run on many distributions), apt, yum, dnf, and zypper. 
+# Additional package manager may be added as time allows. 
+# Usage: 
+# 	call this function using one argument only for reliability reasons; 
+#	as per the below example. If thre is a need to remove a large number of
+#	packages it is reccommended to use a for loop and call this function, 
+#	still realizing the benefit of mylti-distribution support.
+#
+#	rtd_oem_remove_software packagename
+#
+# If a failure occurs this function will return a non "0" exit code. (1)
+# End of documentation
+
+	if [[ $(echo $OSTYPE |grep "linux") ]]; then
+		echo "Trying to remove package $*"
+		if hash pkcon 2>/dev/null; then
+			pkcon remove $* -y --autoremove 
+		elif hash yum 2>/dev/null; then
+			yum -y remove $*
+		elif hash dnf 2>/dev/null; then
+			dnf -y remove $*
+		elif hash apt 2>/dev/null; then
+			apt-get -y --ignore-missing remove $*
+			apt -y autoremove
+		elif hash zypper 2>/dev/null; then
+			zypper -y remove $*
+		else
+			echo -e $YELLOW "This system does not seem to have a software managment system" $ENDCOLOR
+			return 1
+		fi
+	elif [[ "$OSTYPE" == "freebsd"* ]]; then
+		echo "Free BSD is currently unsupported... "
+		return 1
+	else
+		echo "Though you can run bash, I have no Idea how to remove software here!"
+		return 1
+	fi
+}
+
+
+set_install_command () 
+{
 # set_install_command
 # add global install command for portability and convenience
 # If you need to use this script in an rpm based system you could modify the install
@@ -260,11 +341,8 @@ set_install_command () {
 
 
 
-
-
-
-
-enable_firewall () {
+enable_firewall () 
+{
 # enable_firewall
 # Function to enable system firewall and add a given rule. This simple function
 # enables Uncomplicated Fire Wall (UFW) and adds a rule to allow SSH to
@@ -361,7 +439,8 @@ SofwareManagmentAvailabilityCHK ()
 
 
 
-rtd_oem_reset_default_environment_config () {
+rtd_oem_reset_default_environment_config ()
+{
 # Function to reset temporary configurations to their original setings from the
 # distributor. To configure and/or automatically install Linux systems RTD OEM
 # load process must make some changes to the system in question that are not
@@ -380,7 +459,8 @@ rtd_oem_reset_default_environment_config () {
 
 
 
-rtd_wait_for_internet_availability () {
+rtd_wait_for_internet_availability () 
+{
 # Function that, when called, will wait for an active internet connection
 # to be available before before continuing. Most softwrare install activities
 # need an active internet connection to be able to install and update software.
@@ -402,8 +482,8 @@ rtd_wait_for_internet_availability () {
 
 
 
-# up2date ()
-# {
+ up2date ()
+{
 # Function to simplify updating system completely. At present this function sets the
 # highest preference to use "pkcon", the command line interface of "Package Kit" since
 # this is the most consistent across different distrbutions. It may even work on BSD.
@@ -412,31 +492,30 @@ rtd_wait_for_internet_availability () {
 # alias another distributions command (like SuSE does with apt) to be helpfull.
 # This is one of the first update functions written and is kept for compatibility.
 # End of documentation
-# 	echo -e $YELLOW"--- Running up2date function:" $ENDCOLOR
-# 	if [ -z "$_ERRLOGFILE" ]; then $_ERRLOGFILE=$0.log ; else echo "     Logfile is set to: '$_ERRLOGFILE'"; fi
-#         if [ -z "$_LOGFILE" ]; then $_LOGFILE=$0.log ; else echo "     Logfile is set to: '$_LOGFILE'"; fi
+	echo -e $YELLOW"--- Running up2date function:" $ENDCOLOR
 
-#         if hash pkcon 2>/dev/null; then
-# 		pkcon update -y 1>>$_LOGFILE 2>>$_ERRLOGFILE
-# 	elif hash yum 2>/dev/null; then
-# 	        yum update -y 1>>$_LOGFILE 2>>$_ERRLOGFILE
-#         elif hash apt 2>/dev/null; then
-# 	        apt-get update 1>>$_LOGFILE 2>>$_ERRLOGFILE
-# 	        apt-get dist-upgrade -y -qq --allow-change-held-packages --ignore-missing 1>>$_LOGFILE 2>>$_ERRLOGFILE
-# 	        apt-get autoremove -y 1>>$_LOGFILE 2>>$_ERRLOGFILE
-#         elif hash zypper 2>/dev/null; then
-#                 return zypper up 1>>$_LOGFILE 2>>$_ERRLOGFILE
-# 	else
-# 	        return 3
-#         fi
-# }
+	if hash pkcon 2>/dev/null; then
+		pkcon update -y 		1>>$_LOGFILE 2>>$_ERRLOGFILE
+	elif hash yum 2>/dev/null; then
+		yum update -y 			1>>$_LOGFILE 2>>$_ERRLOGFILE
+	elif hash apt 2>/dev/null; then
+		apt-get update 			1>>$_LOGFILE 2>>$_ERRLOGFILE
+		apt-get upgrade -y 		1>>$_LOGFILE 2>>$_ERRLOGFILE
+		apt-get autoremove -y 		1>>$_LOGFILE 2>>$_ERRLOGFILE
+	elif hash zypper 2>/dev/null; then
+		return zypper up -y		1>>$_LOGFILE 2>>$_ERRLOGFILE
+	else
+		return 3
+	fi
+}
 
 
 
 
 
 
-is_software_package_installed (){
+is_software_package_installed ()
+{
 # Function to check if a piece of software is installed. This function will first check
 # if the package manager is deb, zypper or rpm, and then take one parameter passed
 # and evauate if a software package by that name is installed. This function
@@ -494,7 +573,8 @@ is_software_package_available ()
 
 
 
-InstallSoftwareFromRepo (){
+InstallSoftwareFromRepo ()
+{
 # Function to simplify the installation of software by including all display and
 # installation logic for a given software provider. This should be expanded to include flatpack
 # snap for example. It should be the same consistent way no matter flavor of Linux.
@@ -562,7 +642,8 @@ check_dependencies ()
 
 
 
-system_update () {
+system_update () 
+{
 # Function to update the Linux based system. This function is universal for all
 # distributions that have package kit available. It works in the same manner on
 # RedHat/Fedora, Debian/Ubuntu and all their derivatives. When invoked as a
@@ -592,7 +673,8 @@ system_update () {
 
 
 
-rtd_setup_choices_term_fallback () {
+rtd_setup_choices_term_fallback () 
+{
 # Function to display legacy installation options. This will install software that is usefull
 # on a really old system, or a remote system only accessible via SSH. This may be a good
 # usecase if oyu happen to be in an opressed geographic locaiton where your only option is
@@ -602,7 +684,7 @@ rtd_setup_choices_term_fallback () {
 # End of documentation
 
 	# List Options to be available for choice in the RTD System Configurator...
-	cmd=(whiptail --backtitle "RTD OEM System Builder Configuraton Menu" --title "Terminal Software Options Menu" --separate-output --checklist "We did not find a graphical interface. No matter, you can be productive in the cli environment. Please Select Software and Configuration below:" 22 85 16 )
+	cmd=(dialog --backtitle "RTD OEM System Builder Configuraton Menu" --title "Terminal Software Options Menu" --separate-output --checklist "We did not find a graphical interface. No matter, you can be productive in the cli environment. Please Select Software and Configuration below:" 22 85 16 )
 	options=(1 "Base RTD OEM Software" on
 		 2 "Alpine email client" on
 		 3 "Vim text editor" on
@@ -628,60 +710,24 @@ rtd_setup_choices_term_fallback () {
 			for choice in $choices
 			do
 			    case $choice in
-				1)
-				for i in wine-stable ffmpeg netstat nmcli htop powertop iftop monit nethogs bmon darkstat ss mtr glances nmap iostat multitail ncdu multitail ; do InstallSoftwareFromRepo $i ; done
-				;;
-				2)
-				InstallSoftwareFromRepo alpine
-				;;
-				3)
-				InstallSoftwareFromRepo vim
-				;;
-				4)
-				InstallSoftwareFromRepo finch
-				;;
-				5)
-				InstallSoftwareFromRepo	wordgrinder
-				;;
-				6)
-				InstallSoftwareFromRepo sc
-				;;
-				7)
-				InstallSoftwareFromRepo tpp
-				;;
-				8)
-				InstallSoftwareFromRepo mc
-				;;
-				9)
-				InstallSoftwareFromRepo cmus
-				;;
-				10)
-				InstallSoftwareFromRepo byobu
-				;;
-				11)
-				InstallSoftwareFromRepo w3m
-				;;
-				12)
-				InstallSoftwareFromRepo lynx
-				;;
-				13)
-				dl https://mega.nz/linux/MEGAsync/xUbuntu_19.04/amd64/megacmd-*.deb
-				;;
-				14)
-				InstallSoftwareFromRepo rtorrent
-				;;
-				15)
-				InstallSoftwareFromRepo openvpn
-				;;
-				16)
-				InstallSoftwareFromRepo freesweep
-				;;
-				17)
-				InstallSoftwareFromRepo bastet
-				;;
-				18)
-				recipie_OEM_config
-				;;
+				1) for i in netstat nmcli htop powertop iftop monit nethogs bmon darkstat ss mtr glances nmap iostat multitail ncdu multitail ; do InstallSoftwareFromRepo $i ; done ;;
+				2)  InstallSoftwareFromRepo alpine ;;
+				3)  InstallSoftwareFromRepo vim ;;
+				4)  InstallSoftwareFromRepo finch ;;
+				5)  InstallSoftwareFromRepo wordgrinder ;;
+				6)  InstallSoftwareFromRepo sc ;;
+				7)  InstallSoftwareFromRepo tpp ;;
+				8)  InstallSoftwareFromRepo mc ;;
+				9)  InstallSoftwareFromRepo cmus ;;
+				10) InstallSoftwareFromRepo byobu ;;
+				11) InstallSoftwareFromRepo w3m ;;
+				12) InstallSoftwareFromRepo lynx ;;
+				13) dl https://mega.nz/linux/MEGAsync/xUbuntu_19.04/amd64/megacmd-*.deb	;;
+				14) InstallSoftwareFromRepo rtorrent ;;
+				15) InstallSoftwareFromRepo openvpn ;;
+				16) InstallSoftwareFromRepo freesweep ;;
+				17) InstallSoftwareFromRepo bastet ;;
+				18) recipie_OEM_config ;;
 			esac
 		done
 }
@@ -776,7 +822,7 @@ else
 				esac
 			done
 		;;
-		* ) bash $0 --help
+		* ) echo "No RECOGNIZED arguments provided: loading ${0:BASENAME}" ; echo "Use ${0:BASENAME} --help to see supported arguments"
 		;;
 	esac
 fi
