Updates all Admin scripts
Made more consistent and modernized a bit...

diff --git a/System_Admin/rtd-7z-encrypt-all-files-here b/System_Admin/rtd-7z-encrypt-all-files-here
--- a/System_Admin/rtd-7z-encrypt-all-files-here
+++ b/System_Admin/rtd-7z-encrypt-all-files-here
@@ -1,93 +1,77 @@
 #!/bin/bash
 #
-#::             			A D M I N   C O M M A N D L E T   
+#::                                      A D M I N   C O M M A N D
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::// Simple Compression Tool //::::::::::::::::::::::::::::::::::// Linux //::::::::
 #::
-#:: Author:   	SLS  
+#:: Author:   	SLS
 #:: Version 	1.02
 #::
 #::
-#::	Purpose: To compress and encrypt all files and folders individually found in the current folder. 
-#::		 The current folder refers to the present working directory "PWD". 
-#::		 
-#::     Usage:	Simply execute this commandlet to accomplish this task. No parameters required.
-#:: 		Then, when prompted; enter the encryption passphrase you want to use. 
-#::     	it is reccommended to use a password safe like "keepass XC" or similar so the 
-#::     	phrase is not forgotten. 
+#::	Purpose: To compress all files and folders individually found in the current folder.
+#::		 The current folder refers to the present working directory "PWD".
+#::
+#::	Usage:	Simply execute this script to accomplish this task. No parameters required.
+#::
+#::
+#::
 #::
 #::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #
-#
-#
-# This  script was originally developed for RuntimeData, a small OEM in Buffalo Center, IA.
-# This OEM and store nolonger exists as its owner has passed away.
 # This script is shared in the hopes that someone will find it useful.
+# For convenience and supportability most actions (work) is stored in a common library used bu multiple scripts.
+# To use these functions in the library, simply load the library using the "source" bash built in command. All
+# functions will then be available for use. This script demonstrates the simplicity of using these functions.
 #
 # This script is intended to live in the ~/bin/ or /bin/ folder, alternatively in the $PATH.
+# By default this script is placed in /opt/rtd/scrips/
 #
-#
-# Tutorial Text:
-# find ./ -type f -iname "*.rar" -exec unrar e {} \;
-# a                   Add (dir1 to archive.7z)
-# -t7z                Use a 7z archive
-# -m0=lzma2           Use lzma2 method
-# -mx=9               Use the '9' level of compression = Ultra
-# -mfb=64             Use number of fast bytes for LZMA = 64
-# -md=32m             Use a dictionary size = 32 megabytes
-# -ms=on              Solid archive = on
-# -mhe=on             7z format only : enables or disables archive header encryption
-# -p{Password}        Add a password
-# Simple compression logic: 7za a -t7z $line.7z $line
-# To change all filename to have whitespace replaced with _: list=`ls | sed -e 's/ /\\\\ /g'`
-# Alternatively use: IFS=$(echo -en "\n\b") Here IFS is altered to not consider a whitespace as a separator.
-# To see all options type "man 7z"
-# or go to: https://www.mankier.com/1/7z#
+# 1 - To see options to use the rtd library type: "bash _rtd_library --help"
+# 2 - To see usefull documentation on each function in this library: "bash _rtd_library --devhelp"
 
-###########################################################################
-##                                                                       ##
-##                       Set Environment                                 ##
-##                                                                       ##
-###########################################################################
-#
-# Set colors for prompting on screen.
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Settings                 ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+
+# Set default UI colors:
 YELLOW="\033[1;33m"
 RED="\033[0;31m"
 ENDCOLOR="\033[0m"
 
-# Ask for encryption phrase and store it temporarily.
-clear
-echo  Hello $USER ... I am going to compress and encrypt each file or folder that
-echo  I find in this folder. These are:
-echo
-ls -I "*.7z" --color=always
-echo
-echo  To cancel this, just close the terminal or press "CRTL C".
-echo
-echo  To encrypt the content you have to give me a phrase to encrypt it with.
-echo  This can be anything in one long word, but never forget it!
-echo -e $YELLOW
-read -sp 'Enter encryption phrase: ' passtoken
-echo -e $ENDCOLOR
+# Set library path if not defined:
+rtd_library=${rtd_library:-"/opt/rtd/scripts/_rtd_library"}
 
-###########################################################################
-##                                                                       ##
-##                       Script Executive                                ##
-##                                                                       ##
-###########################################################################
-#
-# List everything in the current folder and cpmpress each item.
-# And remember to handle or replace white spaces with underscore so the shell commands
-# don't fail. Here IFS is altered to not consider a whitespace as a separator.
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Functions                ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
-SAVEIFS=$IFS
-IFS=$(echo -en "\n\b")
-  for line in $(ls -I "*.7z")
-   do
-    7z a -t7z -m0=lzma2 -mx=9 -myx=9 -mfb=64 -md=64m -ms=on -mhe=on -v24m -p$passtoken $line.7z $line
-   done
-   IFS=$SAVEIFS
-echo Created the following encrypted files:
-ls *.7z
+check_rtd_library ()
+{
+        if [[ -f ${rtd_library} ]]; then
+                source ${rtd_library}
+        elif [[ ! -f ${rtd_library} ]]; then
+                echo "RTD Functions not found... "
+                echo "Trying to retrieve them..."
+                wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
+                source ./_rtd_library
+        else
+                exit 1
+        fi
+}
+
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Executive                ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+
+check_rtd_library
+
+# Call compression function with encryption option; function will prompt for pasphrase...
+compress_all_items_here --encrypt
diff --git a/System_Admin/rtd-7z-this b/System_Admin/rtd-7z-this
--- a/System_Admin/rtd-7z-this
+++ b/System_Admin/rtd-7z-this
@@ -1,119 +1,79 @@
 #!/bin/bash
 #
-#::             			A D M I N   C O M M A N D L E T   
+#::                                       A D M I N   C O M M A N D
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::// Simple Compression Tool //::::::::::::::::::::::::::::::::::// Linux //::::::::
 #::
-#:: Author:   	SLS  
+#:: Author:   	SLS
 #:: Version 	1.02
 #::
 #::
-#::	Purpose: To compress all files and folders individually found in the current folder. 
-#::		 The current folder refers to the present working directory "PWD". 
-#::		 
-#::     Usage:	Simply execute this commandlet to accomplish this task. No parameters required.
-#:: 
-#::     
-#::     
+#::	Purpose: To compress all files and folders provided as argument.
+#::
+#::
+#::     Usage:	rtd-7z-encrypt-this file1 file2 directory1
+#::
+#::
+#::
 #::
 #::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #
-#
-# This  script was originally developed for RuntimeData, a small OEM in Buffalo Center, IA.
-# This OEM and store nolonger exists as its owner has passed away.
 # This script is shared in the hopes that someone will find it useful.
+# For convenience and supportability most actions (work) is stored in a common library used bu multiple scripts.
+# To use these functions in the library, simply load the library using the "source" bash built in command. All
+# functions will then be available for use. This script demonstrates the simplicity of using these functions.
 #
 # This script is intended to live in the ~/bin/ or /bin/ folder, alternatively in the $PATH.
+# By default this script is placed in /opt/rtd/scrips/
 #
-#
-# Tutorial Text:
-# find ./ -type f -iname "*.rar" -exec unrar e {} \;
-# a                   Add (dir1 to archive.7z)
-# -t7z                Use a 7z archive
-# -m0=lzma2           Use lzma2 method
-# -mx=9               Use the '9' level of compression = Ultra
-# -mfb=64             Use number of fast bytes for LZMA = 64
-# -md=32m             Use a dictionary size = 32 megabytes
-# -ms=on              Solid archive = on
-# -mhe=on             7z format only : enables or disables archive header encryption
-# -p{Password}        Add a password
-# Simple compression logic: 7za a -t7z $line.7z $line
-# To change all filename to have whitespace replaced with _: list=`ls | sed -e 's/ /\\\\ /g'`
-# Alternatively use: IFS=$(echo -en "\n\b") Here IFS is altered to not consider a whitespace as a separator.
-# To see all options type "man 7z"
-# or go to: https://www.mankier.com/1/7z#
+# 1 - To see options to use the rtd library type: "bash _rtd_library --help"
+# 2 - To see usefull documentation on each function in this library: "bash _rtd_library --devhelp"
 
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Settings                 ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
-###########################################################################
-##                                                                       ##
-##                       Set Environment                                 ##
-##                                                                       ##
-###########################################################################
-#
-# Set colors for prompting on screen.
+# Set default UI colors:
+YELLOW="\033[1;33m"
+RED="\033[0;31m"
+ENDCOLOR="\033[0m"
 
-DIR="$*"
-source /opt/rtd/scripts/_rtd_library
- 
-###########################################################################
-##                                                                       ##
-##                       Script Functions                                ##
-##                                                                       ##
-###########################################################################
+# Set library path if not defined:
+rtd_library=${rtd_library:-"/opt/rtd/scripts/_rtd_library"}
 
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Functions                ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
+check_rtd_library ()
+{
+        if [[ -f ${rtd_library} ]]; then
+                source ${rtd_library}
+        elif [[ ! -f ${rtd_library} ]]; then
+                echo "RTD Functions not found... "
+                echo "Trying to retrieve them..."
+                wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
+                source ./_rtd_library
+        else
+                exit 1
+        fi
+}
 
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Executive                ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
+check_rtd_library
 
-
-
-
-###########################################################################
-##                                                                       ##
-##                       Script Executive                                ##
-##                                                                       ##
-###########################################################################
-#
-# List everything in the current folder and cpmpress each item.
-# And remember to handle or replace white spaces with underscore so the shell commands
-# don't fail. Here IFS is altered to not consider a whitespace as a separator.
-
-
-
-[ "$DIR" == "" ] && echo "Usage: rtd-7z-this [filename] [filename filename2] [*.ext]" ; exit 1
-
-# Attempting to deal with filenemes with spaces in them... 
-# Please excuse all the code for a relatively simple task.
-OLDIFS=$IFS
-IFS=$'\n'
-fileArray=($(ls $@))
-IFS=$OLDIFS
-tLen=${#fileArray[@]}
-
-clear
-echo -e  "Hello $YELLOW $USER $ENDCOLOR ... I am going to compress $YELLOW $tLen $ENDCOLOR files: "
-for (( i=0; i<${tLen}; i++ )); do echo -e $GREEN "${fileArray[$i]}        $ENDCOLOR"  ; done
-
-echo  "To cancel this, just close the terminal or press "CRTL C"."
-echo " "
-read -p "Press the [ENTER] key to continue..."
-echo -e "☕ Please be patient as lots of data may take time to compress..."
-
-for (( i=0; i<${tLen}; i++ ));
-do
-	7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=64m -ms=on -mhe=on "${fileArray[$i]}".7z "${fileArray[$i]}"
-done
-
-echo "Created the following archive(s) UN-encrypted:"
-echo " FILENAME         STATUS"
-for (( i=0; i<${tLen}; i++ )); do
-	[[ -e "${fileArray[$i]}".7z ]] && echo -e "$GREEN Confirmed     $ENDCOLOR: $YELLOW "${fileArray[$i]}".7z $ENDCOLOR" || echo -e "$RED Failed!    $ENDCOLOR: $YELLOW "${fileArray[$i]}".7z $ENDCOLOR"
-done
-echo "Please review the output above to review all the progress ⏫"
-
-
+compress_provided_items $*
 
 
 
diff --git a/System_Admin/rtd-add-ubuntu-to-landscape-onprem b/System_Admin/rtd-add-ubuntu-to-landscape-onprem
--- a/System_Admin/rtd-add-ubuntu-to-landscape-onprem
+++ b/System_Admin/rtd-add-ubuntu-to-landscape-onprem
@@ -1,22 +1,22 @@
 #!/bin/bash
 #
-#::             			A D M I N   C O M M A N D L E T   
+#::                                          A D M I N   C O M M A N D
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-#::::::::::::::::::::::::::::::::::::::// Software Setup CMDLET //::::::::::::::::::::::::::::::::::::// Ubuntu //:::::::
+#::::::::::::::::::::::::::::::::::::::// System managment Setup Script //::::::::::::::::::::::::::::// Ubuntu //:::::::
 #::
-#:: Author:   	SLS  
+#:: Author:   	SLS
 #:: Version 	1.00
 #::
 #::
 #::	Purpose: The purpose of the script is to install and configure landscape for ubuntu so it can be managed from
-#::		 a single location. 
-#::		 
+#::		 a single location.
+#::
 #::     Usage:	Simply execute this commandlet to accomplish this task. No parameters required.
 #:: 		Then, when prompted; enter the information requested.
-#::     	
+#::
 #::     	To understand how t use Landscape please refer to: https://landscape.canonical.com/
 #::
-#::     	
+#::
 #::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
@@ -29,76 +29,90 @@
 #
 # This script is intended to live in the ~/bin/ or /bin/ folder, alternatively in the $PATH.
 #
- 
 
-###########################################################################
-##                                                                       ##
-##                         Setup Environment                             ##
-##                                                                       ##
-###########################################################################
-#
-# elevate the privileges to root equivalent
+
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Settings                 ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+
+# Set default UI colors:
 YELLOW="\033[1;33m"
 RED="\033[0;31m"
 ENDCOLOR="\033[0m"
 
-# he name of the local managment server (change to desired name)
-LOCALSERVER=imhothep
+# Set library path if not defined:
+rtd_library=${rtd_library:-"/opt/rtd/scripts/_rtd_library"}
 
-echo -e $YELLOW "This script needs administrative access..." $ENDCOLOR
-[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
+if [ ! "$UID" -eq 0 ]; then
+        if hash dialog 2>/dev/null ; then
+                # find  a diferent way... tempfile not universal...
+                data=$(tempfile 2>/dev/null)
+                trap "rm -f $data" 0 1 2 5 15
+                dialog --title "${Title}" --backtitle "${BackTitle}" --insecure --passwordbox "\n This functionality requires elevated priviledges. \n Please provide your (sudo) password" 10 90 2> $data
+                ret=$? ; clear
+                case $ret in
+                        0) cat $data | sudo -S bash "$0" "$*" ;;
+                        1) echo "Request cancelled" ;;
+                        255) [ -s $data ] && rm $data &>/dev/null || echo "[esc] Request aborted" ;;
+                        * ) rm $data &>/dev/null ; exit 1
+                esac
+                rm $data &>/dev/null
+                exit
+        else
+                [ "$UID" -eq 0 ] || echo "This script needs administrative access..."
+                [ "$UID" -eq 0 ] || exec sudo -H bash "$0" "$@"
+        fi
+fi
 
-#
-###########################################################################
-##                                                                       ##
-##                         Declare Functions                             ##
-##                                                                       ##
-###########################################################################
-#
-# Function to check and see if the system software managment is available
-function SofwareManagmentAvailabilityCHK ()
+
+
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Functions                ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+
+check_rtd_library ()
 {
-echo Checking if software maintenance system is available...
-while [ -f /var/lib/dpkg/lock ] ;
-		do
-			echo "The software managment system is locked..."
-			echo "Waiting 10 seconds for software managment system to be ready:"
-			for i in {0..100}; do echo -ne "$i"'\r'; sleep 1; done; echo
-			echo "force unlocking package managment..."
-			rm -f  /var/lib/apt/lists/lock
-			rm -f /var/lib/dpkg/lock
-	done
+        if [[ -f ${rtd_library} ]]; then
+                source ${rtd_library}
+        elif [[ ! -f ${rtd_library} ]]; then
+                echo "RTD Functions not found... "
+                echo "Trying to retrieve them..."
+                wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
+                source ./_rtd_library
+        else
+                exit 1
+        fi
 }
 
-# Function to simplify updating system completely...
-function up2date ()
-{
-	echo "Running up2date on behalf of $0"
-	echo "-- Refreshing Software repositories..."
-	apt-get update  >>$0.log 2>&1
-	echo "-- Installing System Updates..."
-	apt-get dist-upgrade -y --force-yes >>$0.log 2>&1
-	echo "-- Cleaning up unused software..."
-	apt-get autoremove -y >>$0.log 2>&1
-}
-###########################################################################
-##                                                                       ##
-##                         Execute                                       ##
-##                                                                       ##
-###########################################################################
-#
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Executive                ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+
+check_rtd_library
 up2date
 SofwareManagmentAvailabilityCHK
+check_dependencies dialog
+
+# The name of the local managment server
+LOCALSERVER=$(dialog --title "${Title:="$( basename $0 )"}" --backtitle "${BRANDING:-"$( basename $0 )"}" --stdout --inputbox "\n Please enter the name of the local landscaps server. \n " 10 90 )
+LOCALSERVERIP=$(dialog --title "${Title:="$( basename $0 )"}" --backtitle "${BRANDING:-"$( basename $0 )"}" --stdout --inputbox "\n Please enter the IP Address of the local landscap server. \n " 10 90 )
+# Since landscape is only relevant for Ubuntu; its OK to you distro speciffic commands...
 apt-get install landscape-client -y -q
 echo "ssl_public_key = /etc/landscape/landscape_server_ca.crt" >>/etc/landscape/client.conf
-echo "---------------- clinet.conf  -----------"
+write_status "---------------- clinet.conf  -----------"
 cat /etc/landscape/client.conf
-echo "192.168.1.223       $LOCALSERVER" >>/etc/hosts
-echo "----------------  hosts -----------------"
+echo "${LOCALSERVERIP}       ${LOCALSERVER}" >>/etc/hosts
+write_status "----------------  hosts -----------------"
 cat /etc/hosts
-echo "---------  Get CA from $LOCALSERVER ---------"
-echo Enter password for $LOCALSERVER below:
-scp tangarora@$LOCALSERVER:/etc/landscape/*.crt /etc/landscape/
-sudo landscape-config --computer-title "$HOSTNAME" --account-name standalone  -p $PASSTOKEN --url https://$LOCALSERVER/message-system --ping-url http://$LOCALSERVER/ping
-
+write_status "---------  Get CA from ${LOCALSERVER} ---------"
+echo Enter password for ${LOCALSERVER} below:
+scp ${USER}@${LOCALSERVER}:/etc/landscape/*.crt /etc/landscape/
+landscape-config --computer-title "${HOSTNAME}" --account-name standalone  -p ${PASSTOKEN} --url https://${LOCALSERVER}/message-system --ping-url http://${LOCALSERVER}/ping && result="Sucessfully enrolled with the lanscape server ${LOCALSERVER}" || result="Failed to enroll with the lanscape server ${LOCALSERVER}"
+display_result "$( basename $0 )"
 
diff --git a/System_Admin/rtd-burniso b/System_Admin/rtd-burniso
--- a/System_Admin/rtd-burniso
+++ b/System_Admin/rtd-burniso
@@ -1,36 +1,36 @@
 #!/bin/bash
 #
-#::             			A D M I N   C O M M A N D L E T   
+#::                                           A D M I N   C O M M A N D
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::// Simple bootable CD/DVD creation Tool //:::::::::::::::::::::// Linux //::::::::
 #::
-#:: Author:   	SLS  
+#:: Author:   	SLS
 #:: Version 	1.00
 #::
 #::
-#::	Purpose: The purpose of the script is to write an ISO file to an optical device verbatim. 
-#::		  
-#::		 
-#::     Usage:	Simply execute this commandlet passing the parameter indicating where the ISO is located 
-#:: 		to accomplish this task. 
-#::     	
-#::     	Example: 
+#::	Purpose: The purpose of the script is to write an ISO file to an optical device verbatim.
+#::
+#::
+#::     Usage:	Simply execute this commandlet passing the parameter indicating where the ISO is located
+#:: 		to accomplish this task.
+#::
+#::     	Example:
 #::		rtd-burniso path/to/file.iso
-#::     	
+#::
 #::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #
-# Additional information: 
+# Additional information:
 #
-# An ISO image is a disk image of an optical disc. In other words, it is an archive file that contains everything that would 
-# be written to an optical disc, sector by sector, including the optical disc file system.[1] ISO image files bear the .iso 
-# filename extension. The name ISO is taken from the ISO 9660 file system used with CD-ROM media, but what is known as an 
+# An ISO image is a disk image of an optical disc. In other words, it is an archive file that contains everything that would
+# be written to an optical disc, sector by sector, including the optical disc file system.[1] ISO image files bear the .iso
+# filename extension. The name ISO is taken from the ISO 9660 file system used with CD-ROM media, but what is known as an
 # ISO image might also contain a UDF (ISO/IEC 13346) file system (commonly used by DVDs and Blu-ray Discs).
 #
-# ISO images can be created from optical discs by disk imaging software, or from a collection of files by optical disc authoring 
-# software, or from a different disk image file by means of conversion. Software distributed on bootable discs is often available 
-# for download in ISO image format. And like any other ISO image, it may be written to an optical disc such as CD or DVD. 
+# ISO images can be created from optical discs by disk imaging software, or from a collection of files by optical disc authoring
+# software, or from a different disk image file by means of conversion. Software distributed on bootable discs is often available
+# for download in ISO image format. And like any other ISO image, it may be written to an optical disc such as CD or DVD.
 #
 # This  script was originally developed for RuntimeData, a small OEM in Buffalo Center, IA.
 # This OEM and store nolonger exists as its owner has passed away.
@@ -38,12 +38,42 @@
 #
 # This script is intended to live in the ~/bin/ or /bin/ folder, alternatively in the $PATH.
 #
+###########################################################################
+##                                                                       ##
+##                         Script  settings                              ##
+##                                                                       ##
+###########################################################################
+# Set library path if not defined:
+rtd_library=${rtd_library:-"/opt/rtd/scripts/_rtd_library"}
+if [[ -f ${rtd_library} ]]; then
+        source ${rtd_library}
+elif [[ ! -f ${rtd_library} ]]; then
+        echo "RTD Functions not found... "
+        echo "Trying to retrieve them..."
+        wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
+        source ./_rtd_library
+else
+        exit 1
+fi
 
 ###########################################################################
 ##                                                                       ##
 ##                       Script Executive                                ##
 ##                                                                       ##
 ###########################################################################
+
+if [[ -z "$1" ]]; then
+        echo "You must provide atleast one argument!
+        Example: $0 ~/my_videos.iso"
+        exit 1
+fi
+
+if [[ ! -f "$1" ]]; then
+        echo "The file $1 dies not exist or is not readable!"
+        exit 1
+fi
+
+check_dependencies cdrecord
 
 $IN = $ARGV[0];
 print "Writing the ISO file $IN to the cd... \n";
diff --git a/System_Admin/rtd-clear-zombie b/System_Admin/rtd-clear-zombie
--- a/System_Admin/rtd-clear-zombie
+++ b/System_Admin/rtd-clear-zombie
@@ -1,34 +1,34 @@
 #!/bin/bash
 #
-#::             			A D M I N   C O M M A N D L E T   
+#::                                    A D M I N   C O M M A N D
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::// Simple Admin Tool //::::::::::::::::::::::::::::::::::::::::// Linux //::::::::
 #::
-#:: Author:   	SLS  
+#:: Author:   	SLS
 #:: Version 	1.02
 #::
 #::
-#::	Purpose: The purpose of this script is to clear out zombie processes. 
+#::	Purpose: The purpose of this script is to clear out zombie processes.
 #::		 This may be useful in troubleshooting. It may work, but depending on the cause
-#::		 of the zombification it may or may not work. 
+#::		 of the zombification it may or may not work.
 #::     Usage:	Simply execute this commandlet to accomplish this task. No parameters required.
-#:: 		
-#::     	
-#::     	
+#::
+#::
+#::
 #::
 #::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #
-# Additional Information: 
+# Additional Information:
 #
-# On Unix and Unix-like computer operating systems, a zombie process or defunct process is a process that has completed 
-# execution (via the exit system call) but still has an entry in the process table: it is a process in the "Terminated state". 
-# This occurs for child processes, where the entry is still needed to allow the parent process to read its child's exit status: 
-# once the exit status is read via the wait system call, the zombie's entry is removed from the process table and it is said 
-# to be "reaped". A child process always first becomes a zombie before being removed from the resource table. In most cases, 
-# under normal system operation zombies are immediately waited on by their parent and then reaped by the system – processes 
-# that stay zombies for a long time are generally an error and cause a resource leak. 
+# On Unix and Unix-like computer operating systems, a zombie process or defunct process is a process that has completed
+# execution (via the exit system call) but still has an entry in the process table: it is a process in the "Terminated state".
+# This occurs for child processes, where the entry is still needed to allow the parent process to read its child's exit status:
+# once the exit status is read via the wait system call, the zombie's entry is removed from the process table and it is said
+# to be "reaped". A child process always first becomes a zombie before being removed from the resource table. In most cases,
+# under normal system operation zombies are immediately waited on by their parent and then reaped by the system – processes
+# that stay zombies for a long time are generally an error and cause a resource leak.
 #
 # This  script was originally developed for RuntimeData, a small OEM in Buffalo Center, IA.
 # This OEM and store nolonger exists as its owner has passed away.
@@ -42,14 +42,27 @@
 ##                                                                       ##
 ###########################################################################
 
-# Set display colors for usability
-YELLOW="\033[1;33m"
-RED="\033[0;31m"
-ENDCOLOR="\033[0m"
-
 # Elevate priveledges to administrate system
-echo -e $YELLOW "This script needs administrative access..." $ENDCOLOR
-[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
+if [ ! "$UID" -eq 0 ]; then
+        if hash dialog 2>/dev/null ; then
+                # find  a diferent way... tempfile not universal...
+                data=$(tempfile 2>/dev/null)
+                trap "rm -f $data" 0 1 2 5 15
+                dialog --title "${Title}" --backtitle "${BackTitle}" --insecure --passwordbox "\n This functionality requires elevated priviledges. \n Please provide your (sudo) password" 10 90 2> $data
+                ret=$? ; clear
+                case $ret in
+                        0) cat $data | sudo -S bash "$0" "$*" ;;
+                        1) echo "Request cancelled" ;;
+                        255) [ -s $data ] && rm $data &>/dev/null || echo "[esc] Request aborted" ;;
+                        * ) rm $data &>/dev/null ; exit 1
+                esac
+                rm $data &>/dev/null
+                exit
+        else
+                [ "$UID" -eq 0 ] || echo "This script needs administrative access..."
+                [ "$UID" -eq 0 ] || exec sudo -H bash "$0" "$@"
+        fi
+fi
 
 
 ###########################################################################
@@ -58,4 +71,5 @@ echo -e $YELLOW "This script needs administrative access..." $ENDCOLOR
 ##                                                                       ##
 ###########################################################################
 
-kill $(ps -A -ostat,ppid | awk '/[zZ]/{print $2}')
+result=$(kill $(ps -A -ostat,ppid | awk '/[zZ]/{print $2}'))
+display_result "$( basename $0 )"
diff --git a/System_Admin/rtd-clear_iptables b/System_Admin/rtd-clear_iptables
--- a/System_Admin/rtd-clear_iptables
+++ b/System_Admin/rtd-clear_iptables
@@ -1,20 +1,20 @@
 #!/bin/bash
 #
-#::             			A D M I N   C O M M A N D L E T   
+#::                                    A D M I N   C O M M A N D
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::// Simple Admin Tool //::::::::::::::::::::::::::::::::::::::::// Linux //::::::::
 #::
-#:: Author:   	SLS  
+#:: Author:   	SLS
 #:: Version 	1.02
 #::
 #::
-#::	Purpose: The purpose of this script is to do som cleaning of iptables. 
-#::		 This may be useful in troubleshooting. 
-#::		 
+#::	Purpose: The purpose of this script is to do som cleaning of iptables.
+#::		 This may be useful in troubleshooting.
+#::
 #::     Usage:	Simply execute this commandlet to accomplish this task. No parameters required.
-#:: 		
-#::     	
-#::     	
+#::
+#::
+#::
 #::
 #::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
@@ -35,8 +35,27 @@
 ###########################################################################
 
 # Elevate the privileges to root equivalent (if not already) to manage system...
-[ "$UID" -eq 0 ] || echo "This script needs administrative access..."
-[ "$UID" -eq 0 ] || exec sudo -H bash "$0" "$@"
+
+if [ ! "$UID" -eq 0 ]; then
+        if hash dialog 2>/dev/null ; then
+                # find  a diferent way... tempfile not universal...
+                data=$(tempfile 2>/dev/null)
+                trap "rm -f $data" 0 1 2 5 15
+                dialog --title "${Title}" --backtitle "${BackTitle}" --insecure --passwordbox "\n This functionality requires elevated priviledges. \n Please provide your (sudo) password" 10 90 2> $data
+                ret=$? ; clear
+                case $ret in
+                        0) cat $data | sudo -S bash "$0" "$*" ;;
+                        1) echo "Request cancelled" ;;
+                        255) [ -s $data ] && rm $data &>/dev/null || echo "[esc] Request aborted" ;;
+                        * ) rm $data &>/dev/null ; exit 1
+                esac
+                rm $data &>/dev/null
+                exit
+        else
+                [ "$UID" -eq 0 ] || echo "This script needs administrative access..."
+                [ "$UID" -eq 0 ] || exec sudo -H bash "$0" "$@"
+        fi
+fi
 
 
 ###########################################################################
diff --git a/System_Admin/rtd-configure-huion b/System_Admin/rtd-configure-huion
--- a/System_Admin/rtd-configure-huion
+++ b/System_Admin/rtd-configure-huion
@@ -1,20 +1,20 @@
 #!/bin/bash
 #
-#::             			A D M I N   C O M M A N D L E T   
+#::             			A D M I N   C O M M A N D L E T
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::// Simple Admin Tool //::::::::::::::::::::::::::::::::::::::::// Linux //::::::::
 #::
-#:: Author:   	SLS  
+#:: Author:   	SLS
 #:: Version 	1.02
 #::
 #::
-#::	Purpose: The purpose of this script is to configure a Huion tablet. 
+#::	Purpose: The purpose of this script is to configure a Huion tablet.
 #::		 This is available for convenience only. Sucess may vary.
-#::		 
+#::
 #::     Usage:	Simply execute this commandlet to accomplish this task. No parameters required.
 #:: 		NOTE: Please refer to: https://www.huion.com/pen_tablet/
-#::     	
-#::     	
+#::
+#::
 #::
 #::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
@@ -31,37 +31,22 @@
 
 # Import the RTD functions to gain access to several useful functions.
 
-# Set colors for prompting on screen.
-	YELLOW="\033[1;33m"
-	RED="\033[0;31m"
-	ENDCOLOR="\033[0m"
-	GREEN="\033[0;32m"
-	BLUE="\033[0;34m"
-	
-if [ -f ~/bin/_rtd_functions ]; then 
-	source ~/bin/_rtd_functions
-else 
-	if -f [ /opt/rtd/scripts/_rtd_functions ]; then 
-		source /opt/rtd/scripts/_rtd_functions
-	else 
-		echo "RTD Functions not found... "
-		echo "Trying to retrieve them..."
-		wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_functions 
-		source ./_rtd_functions
-	fi
-fi
-
-if [[ "$RTDFUCTIONS" = "1" ]]
-      then
-        echo -e $GREEN "RTD functions loaded!" $ENDCOLOR
-      else
-        echo -e $RED "RTD functions NOT loaded!" $ENDCOLOR
-        echo -e $YELLOW "Will try to proceed without the ability to" $ENDCOLOR
-        echo -e $YELLOW "ensure that the correct software is available" $ENDCOLOR
-        echo -e $YELLOW "Assuming that all is setup correctly for this CMDLET" $ENDCOLOR
-fi
+check_rtd_library ()
+{
+        if [[ -f ${rtd_library} ]]; then
+                source ${rtd_library}
+        elif [[ ! -f ${rtd_library} ]]; then
+                echo "RTD Functions not found... "
+                echo "Trying to retrieve them..."
+                wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
+                source ./_rtd_library
+        else
+                exit 1
+        fi
+}
 
 
 
+check_rtd_library
 ensure_admin
 config_huion610
diff --git a/System_Admin/rtd-dropbox-on-ecryptfs b/System_Admin/rtd-dropbox-on-ecryptfs
--- a/System_Admin/rtd-dropbox-on-ecryptfs
+++ b/System_Admin/rtd-dropbox-on-ecryptfs
@@ -1,20 +1,20 @@
 #!/bin/bash
 #
-#::             			A D M I N   C O M M A N D L E T   
+#::             			A D M I N   C O M M A N D L E T
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::// Simple Admin Tool //::::::::::::::::::::::::::::::::::::::::// Linux //::::::::
 #::
-#:: Author:   	SLS  
+#:: Author:   	SLS
 #:: Version 	1.02
 #::
 #::
-#::	Purpose: The purpose of this script is to migrate a users dropbox folder to a volume 
-#::		 that is loopmounted and formatted with extfs4. This may be needed if the dropbox folder 
-#::		 needs to reside on a Luks encrypted home folder; wich Dropbox has dropped support for. 
+#::	Purpose: The purpose of this script is to migrate a users dropbox folder to a volume
+#::		 that is loopmounted and formatted with extfs4. This may be needed if the dropbox folder
+#::		 needs to reside on a Luks encrypted home folder; wich Dropbox has dropped support for.
 #::     Usage:	Simply execute this commandlet to accomplish this task. No parameters required.
-#:: 		
-#::     	
-#::     	
+#::
+#::
+#::
 #::
 #::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
@@ -30,17 +30,20 @@
 
 
 
+if [[ -d ~/Dropbox ]]; then
+        killall dropbox
+        mv Dropbox Dropbox.bak
+        mkdir Dropbox
+        dd if=/dev/zero of=~/.dropbox/storage bs=1M count=14072
+        mkfs.ext4 /home/$USER/.dropbox/storage
+        chattr +i /home/$USER/Dropbox
+        /home/$USER/.dropbox/storage /home/$USER/Dropbox ext4 defaults,user_xattr,loop 0 0
+        mount /home/$USER/Dropbox/
 
 
-killall dropbox
-mv Dropbox Dropbox.bak
-mkdir Dropbox
-dd if=/dev/zero of=~/.dropbox/storage bs=1M count=14072
-mkfs.ext4 /home/$USER/.dropbox/storage
-chattr +i /home/$USER/Dropbox
-/home/$USER/.dropbox/storage /home/$USER/Dropbox ext4 defaults,user_xattr,loop 0 0
-mount /home/$USER/Dropbox/
-
-
-chown -R $USER /home/$USER/Dropbox
-cp -a Dropbox.bak/* Dropbox/
+        chown -R $USER /home/$USER/Dropbox
+        cp -a Dropbox.bak/* Dropbox/
+else
+        echo "Dropbox folder not found!"
+        exit 1
+fi
diff --git a/System_Admin/rtd-get-Windows-product-key b/System_Admin/rtd-get-Windows-product-key
--- a/System_Admin/rtd-get-Windows-product-key
+++ b/System_Admin/rtd-get-Windows-product-key
@@ -2,7 +2,7 @@
 #
 #::              			A D M I N   C O M M A N D L E T
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-#::::::::::::::::::::::::::::::::::::::// Simple Compression Tool //::::::::::::::::::::::::::::::::::// Linux //::::::::
+#::::::::::::::::::::::::::::::::::::::::::::// Simple Admin Tool //::::::::::::::::::::::::::::::::::// Linux //::::::::
 #::
 #:: Author:   	SLS
 #:: Version 	1.00
@@ -26,11 +26,20 @@
 # This script is intended to live in the ~/bin/ or /bin/ folder, alternatively in the $PATH.
 #
 
-
-
-
-
-source /opt/rtd/scripts/_rtd_library &>/dev/null
+check_rtd_library ()
+{
+        if [[ -f ${rtd_library} ]]; then
+                source ${rtd_library}
+        elif [[ ! -f ${rtd_library} ]]; then
+                echo "RTD Functions not found... "
+                echo "Trying to retrieve them..."
+                wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
+                source ./_rtd_library
+        else
+                exit 1
+        fi
+}
+check_rtd_library
 get_Windows_Product_Key
 
 
diff --git a/System_Admin/rtd-internet-location b/System_Admin/rtd-internet-location
--- a/System_Admin/rtd-internet-location
+++ b/System_Admin/rtd-internet-location
@@ -1,8 +1,8 @@
 #!/bin/bash
 #
-#::             			A D M I N   C O M M A N D L E T   
+#::             			A D M I N   C O M M A N D
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-#::::::::::::::::::::::::::::::::::::::// Simple Admin Tool //:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::// Simple Admin Tool //::::::::::::::::::::::::::::::::::::::::// Linux //::::::::
 #::
 #:: Author:   	SLS
 #:: Version 	1.00
@@ -11,9 +11,9 @@
 #::		* File originally created.
 #::
 #::
-#::	Purpose: The purpose of the script is to find and display you internet location (geolocation) 
-#:: 	 	 Executing this command will identify you external IP and where physically it is located. 
-#::		 This is a useful function to quickly check if you VPN is working correctly. 
+#::	Purpose: The purpose of the script is to find and display you internet location (geolocation)
+#:: 	 	 Executing this command will identify you external IP and where physically it is located.
+#::		 This is a useful function to quickly check if you VPN is working correctly.
 #::
 #::
 #::
@@ -28,41 +28,22 @@
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
 
-_LOCALINT="ens3"
-_VPNINT="tun0"
-_LOCALNET="192.168.1.0"
-_LOCALSUB="24"
 
-# Set colors for prompting on screen.
-	YELLOW="\033[1;33m"
-	RED="\033[0;31m"
-	ENDCOLOR="\033[0m"
-	GREEN="\033[0;32m"
-	BLUE="\033[0;34m"
-	
-if [ -f ~/bin/_rtd_functions ]; then 
-	source ~/bin/_rtd_functions
-else 
-	if [ -f /opt/rtd/scripts/_rtd_functions ]; then 
-		source /opt/rtd/scripts/_rtd_functions
-	else 
-		echo "RTD Functions not found... "
-		echo "Trying to retrieve them..."
-		wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_functions 
-		source ./_rtd_functions
-	fi
-fi
+check_rtd_library ()
+{
+        if [[ -f ${rtd_library} ]]; then
+                source ${rtd_library}
+        elif [[ ! -f ${rtd_library} ]]; then
+                echo "RTD Functions not found... "
+                echo "Trying to retrieve them..."
+                wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
+                source ./_rtd_library
+        else
+                exit 1
+        fi
+}
 
-if [ "$RTDFUCTIONS" -eq "1" ]
-      then
-        echo -e $GREEN "RTD functions loaded!" $ENDCOLOR
-      else
-        echo -e $RED "RTD functions NOT loaded!" $ENDCOLOR
-        echo -e $YELLOW "Will try to proceed without the ability to" $ENDCOLOR
-        echo -e $YELLOW "ensure that the correct software is available" $ENDCOLOR
-        echo -e $YELLOW "Assuming that all is setup correctly for this CMDLET" $ENDCOLOR
-fi
-
+check_rtd_library
 # This script relies on curl to send web content to standard out (screen)
 # so we need to ensure that this is available on the system.
 check_dependencies curl
diff --git a/System_Admin/rtd-join-avi b/System_Admin/rtd-join-avi
--- a/System_Admin/rtd-join-avi
+++ b/System_Admin/rtd-join-avi
@@ -1,36 +1,36 @@
 #!/bin/bash
 #
-#::             			A D M I N   C O M M A N D L E T   
+#::             			A D M I N   C O M M A N D
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-#::::::::::::::::::::::::::::::::::::::// Simple bootable CD/DVD creation Tool //:::::::::::::::::::::// Linux //::::::::
+#::::::::::::::::::::::::::::::::::::::// Simple AVI joiner Tool //:::::::::::::::::::::::::::::::::::// Linux //::::::::
 #::
-#:: Author:   	SLS  
+#:: Author:   	SLS
 #:: Version 	1.00
 #::
 #::
-#::	Purpose: The purpose of the script is to write an ISO file to an optical device verbatim. 
-#::		  
-#::		 
-#::     Usage:	Simply execute this commandlet passing the parameter indicating where the ISO is located 
-#:: 		to accomplish this task. 
-#::     	
-#::     	Example: 
-#::		rtd-burniso path/to/file.iso
-#::     	
+#::	Purpose: The purpose of the script is to join avi files in to one playable movie.
+#::
+#::
+#::     Usage:	Simply execute this commandlet passing the parameter indicating where avi files are located
+#:: 		to join them all in one file.
+#::
+#::     	Example:
+#::		rtd-join-avi *.avi
+#::
 #::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #
-# Additional information: 
+# Additional information:
 #
-# An ISO image is a disk image of an optical disc. In other words, it is an archive file that contains everything that would 
-# be written to an optical disc, sector by sector, including the optical disc file system.[1] ISO image files bear the .iso 
-# filename extension. The name ISO is taken from the ISO 9660 file system used with CD-ROM media, but what is known as an 
-# ISO image might also contain a UDF (ISO/IEC 13346) file system (commonly used by DVDs and Blu-ray Discs).
-#
-# ISO images can be created from optical discs by disk imaging software, or from a collection of files by optical disc authoring 
-# software, or from a different disk image file by means of conversion. Software distributed on bootable discs is often available 
-# for download in ISO image format. And like any other ISO image, it may be written to an optical disc such as CD or DVD. 
+# Audio Video Interleave (also Audio Video Interleaved), known by its initials AVI and the .avi filename extension,
+# is a multimedia container format introduced by Microsoft in November 1992 as part of its Video for Windows software.
+# AVI files can contain both audio and video data in a file container that allows synchronous audio-with-video playback.
+# Like the DVD video format, AVI files support multiple streaming audio and video, although these features are seldom used.
+
+# Many AVI files use the file format extensions developed by the Matrox OpenDML group in February 1996. These files
+# are supported by Microsoft, and are unofficially called "AVI 2.0". In 2010 the US government's National Archives and
+# Records Administration defined AVI as the official wrapper for preserving digital video.
 #
 # This  script was originally developed for RuntimeData, a small OEM in Buffalo Center, IA.
 # This OEM and store nolonger exists as its owner has passed away.
@@ -46,39 +46,20 @@
 #::::::::::::::                                          ::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
-# Set colors for prompting on screen.
-	YELLOW="\033[1;33m"
-	RED="\033[0;31m"
-	ENDCOLOR="\033[0m"
-	GREEN="\033[0;32m"
-	BLUE="\033[0;34m"
 
-
-if [ -f ~/bin/_rtd_functions ]; then 
-	source ~/bin/_rtd_functions
-else 
-	if -f [ /opt/rtd/scripts/_rtd_functions ]; then 
-		source /opt/rtd/scripts/_rtd_functions
-	else 
-		echo "RTD Functions not found... "
-		echo "Trying to retrieve them..."
-		wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_functions 
-		source ./_rtd_functions
-	fi
-fi
-
-
-
-if [[ "$RTDFUCTIONS" = "1" ]]
-      then
-        echo -e $GREEN "RTD functions loaded!" $ENDCOLOR
-      else
-        echo -e $RED "RTD functions NOT loaded!" $ENDCOLOR
-        echo -e $YELLOW " " $ENDCOLOR
-        echo -e $YELLOW "Cannit ensure that the correct software is available" $ENDCOLOR
-        echo -e $YELLOW "Quiting rather than cause potential damage..." $ENDCOLOR
-        exit 1
-fi
+check_rtd_library ()
+{
+        if [[ -f ${rtd_library} ]]; then
+                source ${rtd_library}
+        elif [[ ! -f ${rtd_library} ]]; then
+                echo "RTD Functions not found... "
+                echo "Trying to retrieve them..."
+                wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
+                source ./_rtd_library
+        else
+                exit 1
+        fi
+}
 
 
 ###########################################################################
@@ -86,14 +67,30 @@ fi
 ##                       Script Executive                                ##
 ##                                                                       ##
 ###########################################################################
-check_dependencies mencoder
-check_dependencies dialog
+
+if ! hash mencoder 2>/dev/null; then
+	if [[ "$UID" == "0" ]]; then
+		check_dependencies mencoder
+		exit
+	else
+		write_error "Software needed to join AVI files is missing. Please run $( basename $0 ) again with sudo so that I may correct the problem."
+		exit
+	fi
+fi
+
+if [[ -z $1 ]]; then
+	write_error "You need to provide at least one argument!
+	for example: $( basename $0 ) *.avi
+	so that I know what files to process! "
+	exit
+fi
+
 
 
 rtd_join_avis () {
-        mencoder -oac copy -ovc copy *.avi -o WHOLE-THING.avi
+        mencoder -oac copy -ovc copy $@ -o WHOLE-THING.avi
 }
 
-
+check_rtd_library
 rtd_join_avis
- 
+
diff --git a/System_Admin/rtd-on-notify-wait b/System_Admin/rtd-on-notify-wait
--- a/System_Admin/rtd-on-notify-wait
+++ b/System_Admin/rtd-on-notify-wait
@@ -1,20 +1,20 @@
 #!/bin/bash
 #
-#::                                      A D M I N   C O M M A N D L E T   
+#::                                      A D M I N   C O M M A N D L E T
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::// Simple Admin Tool //::::::::::::::::::::::::::::::::::::::::// Linux //::::::::
 #::
-#:: Author:   	SLS  
+#:: Author:   	SLS
 #:: Version 	1.02
 #::
 #::
-#::	Purpose: The purpose of this script is to clear out zombie processes. 
+#::	Purpose: The purpose of this script is to clear out zombie processes.
 #::		 This may be useful in troubleshooting. It may work, but depending on the cause
-#::		 of the zombification it may or may not work. 
+#::		 of the zombification it may or may not work.
 #::     Usage:	Simply execute this commandlet to accomplish this task. No parameters required.
-#:: 		
-#::     	
-#::     	
+#::
+#::
+#::
 #::
 #::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
@@ -48,46 +48,18 @@
 #    rtd-on-notify-wait rsync -avt . host:/remote/dir
 #
 #
-
-if hash inotifywait 2>/dev/null; then
-	echo "I found that inotifywait is present on this system... thankyou for that! "
+rtd_library=${rtd_library:-"/opt/rtd/scripts/_rtd_library"}
+if [[ -f ${rtd_library} ]]; then
+        source ${rtd_library}
+elif [[ ! -f ${rtd_library} ]]; then
+        echo "RTD Functions not found... "
+        echo "Trying to retrieve them..."
+        wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
+        source ./_rtd_library
 else
-	echo "You seem to have no inotifywait.. I will try to get it... "
-	apt install inotify-tools -y
-	if [ $? != 0 ];
-	then
-		echo "That install didn't work out so well."
-		echo "Please manually try to add the software since I couldn't do it."
-		exit
-	fi
-	echo "OK Done! Continuing..."
+        exit 1
 fi
 
 
-EVENTS="CREATE,CLOSE_WRITE,DELETE,MODIFY,MOVED_FROM,MOVED_TO"
 
-if [ -z "$1" ]; then
-	echo "Usage: $0 rsync -avt . host:/remote/dir ..."
-	exit -1;
-fi
-
-inotifywait -e "$EVENTS" -m -r --format '%:e %f' . | (
-	WAITING="";
-	while true; do
-	LINE="";
-	read -t 1 LINE;
-	if test -z "$LINE"; then
-		if test ! -z "$WAITING"; then
-			echo "CHANGE";
-			WAITING="";
-		fi;
-	else
-		WAITING=1;
-	fi;
-	done) | (
-	while true; do
-	read TMP;
-	echo $@
-	$@
-	done
-)
+io_on_notify_wait
diff --git a/System_Admin/rtd-ppa-checker b/System_Admin/rtd-ppa-checker
--- a/System_Admin/rtd-ppa-checker
+++ b/System_Admin/rtd-ppa-checker
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-#::                                            A D M I N   C O M M A N D L E T   
+#::                                            A D M I N   C O M M A N D L E T
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::// Simple Admin Tool //::::::::::::::::::::::::::::::::::::::::// Ubuntu //:::::::
 #::
@@ -8,12 +8,12 @@
 #:: Version 	1.02
 #::
 #::
-#::	Purpose: The purpose of this script is to clear out unused PPA repositories. 
-#::		 
-#::		
+#::	Purpose: The purpose of this script is to clear out unused PPA repositories.
+#::
+#::
 #::     Usage:	Simply execute this commandlet to list the PPA repositories and how many packages
 #:: 		are installed from each repository. To remove the unused repositories use the --delete option:
-#::     	
+#::
 #::     	rtd-ppa-checker --delete
 #::
 #::
@@ -21,31 +21,17 @@
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #
 #
-for f in /etc/apt/sources.list.d/*.list; do
-	grep -Po "(?<=^deb\s).*?(?=#|$)" "$f" | while read -r ENTRY ; do
-		echo "ENTRY: $ENTRY"
-		HOST=$(cut -d/ -f3 <<< "$ENTRY")
+rtd_library=${rtd_library:-"/opt/rtd/scripts/_rtd_library"}
+if [[ -f ${rtd_library} ]]; then
+        source ${rtd_library}
+elif [[ ! -f ${rtd_library} ]]; then
+        echo "RTD Functions not found... "
+        echo "Trying to retrieve them..."
+        wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
+        source ./_rtd_library
+else
+        exit 1
+fi
 
-		if [ "ppa.launchpad.net" = "$HOST" ]; then
-			USER=$(cut -d/ -f4 <<< "$ENTRY")
-			PPA=$(cut -d/ -f5 <<< "$ENTRY")
-			packageCount=$(awk '$1=="Package:" {if (a[$2]++ == 0) {system("dpkg -l "$2)}}' /var/lib/apt/lists/*"$USER"*"$PPA"*Packages 2>/dev/null | awk '/^ii/' | wc -l)
-			echo "PPA: ppa:$USER/$PPA"
-			echo "FILENAME: $f"
-			echo "$packageCount package(s) installed"
-			if [ "$packageCount" -eq 0 ] && [ "$1" == "--delete" ]; then
-				sudo rm "$f" && echo "$f deleted"
-			fi
-		else 
-			USER=$(cut -d/ -f3 <<< "$ENTRY")
-			PPA=$(cut -d/ -f4 <<< "$ENTRY")
-			packageCount=$(awk '$1=="Package:" {if (a[$2]++ == 0) {system("dpkg -l "$2)}}' /var/lib/apt/lists/*"$USER"*Packages 2>/dev/null | awk '/^ii/' | wc -l)
-			echo "REPOSITORY: $USER/$PPA"
-			echo "FILENAME: $f"
-			echo "$packageCount package(s) installed"
-			if [ "$packageCount" -eq 0 ] && [ "$1" == "--delete" ]; then
-				sudo rm "$f" && echo "$f deleted" 
-			fi
-		fi
-	done
-done
+ensure_admin
+rtd_ppa_checker
diff --git a/System_Setup/_rtd_library b/System_Setup/_rtd_library
--- a/System_Setup/_rtd_library
+++ b/System_Setup/_rtd_library
@@ -610,6 +610,39 @@ rtd_wait_for_internet_availability ()
 
 
 
+io_on_notify_wait ()
+{
+	check_dependencies inotify-tools
+	EVENTS="CREATE,CLOSE_WRITE,DELETE,MODIFY,MOVED_FROM,MOVED_TO"
+
+	if [ -z "$1" ]; then
+		echo "Usage: $0 rsync -avt . host:/remote/dir ..."
+		exit -1;
+	fi
+
+	inotifywait -e "$EVENTS" -m -r --format '%:e %f' . | (
+		WAITING="";
+		while true; do
+		LINE="";
+		read -t 1 LINE;
+		if test -z "$LINE"; then
+			if test ! -z "$WAITING"; then
+				echo "CHANGE";
+				WAITING="";
+			fi;
+		else
+			WAITING=1;
+		fi;
+		done) | (
+		while true; do
+		read TMP;
+		echo $@
+		$@
+		done
+	)
+}
+
+
 
 
 
@@ -1452,14 +1485,28 @@ ensure_admin ()
 # ensure_admin
 #
 # End of documentation
-
 	if [ ! "$UID" -eq 0 ]; then
-		write_warning "This script needs administrative access..."
-		sudo bash "$0" "$*"
-		exit
-	else
-		if xset q &>/dev/null; then xhost local:root ; fi
+		if hash dialog 2>/dev/null ; then
+			# find  a diferent way... tempfile not universal...
+			data=$(tempfile 2>/dev/null)
+			trap "rm -f $data" 0 1 2 5 15
+			dialog --title "${Title}" --backtitle "${BackTitle}" --insecure --passwordbox "\n This functionality requires elevated priviledges. \n Please provide your (sudo) password" 10 90 2> $data
+			ret=$? ; clear
+			case $ret in
+				0) cat $data | sudo -S bash "$0" "$*" ;;
+				1) echo "Request cancelled" ;;
+				255) [ -s $data ] && rm $data &>/dev/null || echo "[esc] Request aborted" ;;
+				* ) rm $data &>/dev/null ; exit 1
+			esac
+			rm $data &>/dev/null
+			exit
+		else
+			write_warning "This script needs administrative access..."
+			sudo bash "$0" "$*"
+			exit
+		fi
 	fi
+	if xset q &>/dev/null; then xhost local:root ; fi
 }
 
 
@@ -2471,15 +2518,16 @@ compress_all_items_here ()
 #		is 7z. This privides a high level of compression.
 #
 # Globals:
-# Arguments: None
+# Arguments: --noprompt, --encrypt (mutually exclusive)
 # Outputs:
 # Returns:
-# Usage:
+# Usage:	compress_all_items_here [--compress] [--noprompt]
 # Usage:	Simply call this function to accomplish this task.
 #
-# Arguments:	No parameters required.
+# Arguments:	No parameters required for basic function (user will be prompted).
 #
 # End of documentation
+
 	if hash 7z ; then
 		write_information "7z is present, good..."
 	else
@@ -2495,33 +2543,146 @@ compress_all_items_here ()
 		done
 	fi
 
-	if hash dialog 2>/dev/null ; then
-		if ( dialog --backtitle "${BRANDING:-"${FUNCNAME[0]}"}" --title "Compress Content Here" --colors --cr-wrap --no-collapse --no-button "NO: Quit" --yes-button "YES: Compress" --yesno "Hello ${USER}... I am going to compress each file or folder that I find here: $(pwd) These are: \Z5 \n$(ls -h1 -F -I "*.7z")" 20 90 ); then
-			clear
-			continue
+	if [[ ! "$1" == "--noprompt" ]]; then
+		if hash dialog 2>/dev/null ; then
+			if ( dialog --backtitle "${BRANDING:-"${FUNCNAME[0]}"} ${1}" --title "Compress Content Here" --colors --cr-wrap --no-collapse --no-button "NO: Quit" --yes-button "YES: Compress" --yesno "Hello ${USER}... I am going to compress each file or folder that I find here: $(pwd) These are: \Z5 \n$(ls -h1 -F -I "*.7z")" 20 90 ); then
+				clear
+			else
+				clear
+				exit
+			fi
 		else
 			clear
-			exit
+			write_host --cyan  "Hello ${USER}... I am going to compress each file or folder that I find in this folder. These are:"
+			ls -I "*.7z" --color=always
+			echo -e " \n"
+			write_information "To cancel this, just close the terminal or press [CRTL] + [C]."
+			read -p "Press the [ENTER] key to continue..."
 		fi
-	else
-		clear
-		write_host --cyan  "Hello ${USER}... I am going to compress each file or folder that I find in this folder. These are:"
-		ls -I "*.7z" --color=always
-		echo -e " \n"
-		write_information "To cancel this, just close the terminal or press [CRTL] + [C]."
-		read -p "Press the [ENTER] key to continue..."
 	fi
 
-	SAVEIFS=$IFS
-	IFS=$(echo -en "\n\b")
-	for line in $(ls -I "*.7z")
-	do
-		7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=64m -ms=on -mhe=on $line.7z $line
-	done
-	IFS=$SAVEIFS
-	write_information "Created the following archives un-encrypted:"
-	ls *.7z
+
+	if echo ${*} |grep "encrypt" ; then
+		passtoken=$(dialog --title "${Title:="$( basename $0 )"}" --backtitle "${BRANDING:-"${FUNCNAME[0]}"}" --stdout --insecure --passwordbox "\n Please provide a passphrase for the encryption. \n Please do not forget it!" 10 90 )
+		ret=$? ; clear
+		case $ret in
+			0)
+				SAVEIFS=$IFS
+				IFS=$(echo -en "\n\b")
+				for line in $(ls -I "*.7z")
+				do
+					7z a -t7z -m0=lzma2 -mx=5 -mfb=64 -md=64m -ms=on -mhe=on -p$passtoken $line.7z $line
+				done
+				IFS=$SAVEIFS
+				result="
+				\n Created the following archives encrypted with a pass-phrase:
+
+				\n \Z1  $(ls *.7z)"
+				display_result "Done creating encrypted archives"
+			;;
+			1) echo "Request cancelled" ; exit 1;;
+			255) echo "[esc] Request aborted" ; exit 255;;
+			* )  exit 1 ;;
+		esac
+	else
+		SAVEIFS=$IFS
+		IFS=$(echo -en "\n\b")
+		for line in $(ls -I "*.7z")
+		do
+			7z a -t7z -m0=lzma2 -mx=5 -mfb=64 -md=64m -ms=on -mhe=on $line.7z $line
+		done
+		IFS=$SAVEIFS
+		result="
+		Created the following archives un-encrypted:
+
+		\n \Z1  $(ls *.7z)"
+		display_result "Done Compressing"
+	fi
 }
+
+
+
+
+
+
+compress_provided_items ()
+{
+# Description: Function to compress the contents of the present working directory.
+#
+# Purpose:	To compress all files and folders individually found in the current folder.
+#		The current folder refers to the present working directory "PWD". Compression method
+#		is 7z. This privides a high level of compression.
+#
+# Globals:
+# Arguments: --noprompt, --encrypt (mutually exclusive)
+# Outputs:
+# Returns:
+# Usage:	compress_all_items_here [--compress] [--noprompt]
+# Usage:	Simply call this function to accomplish this task.
+#
+# Arguments:	No parameters required for basic function (user will be prompted).
+#
+# End of documentation
+list="$*"
+	if echo ${1} |grep "encrypt" ; then
+		passtoken=$(dialog --title "${Title:="$( basename $0 )"}" --backtitle "${BRANDING:-"${FUNCNAME[0]}"}" --stdout --insecure --passwordbox "\n To encrypt the content you have to give me a phrase to encrypt it with. \n This can be anything in one long word, but never forget it!" 10 90 )
+		ret=$? ; clear
+		case $ret in
+			0)
+
+				echo "☕ Please be patient, Large sets of files may take serious time..."
+				list="${list:9:1000}"
+				SAVEIFS=$IFS
+				IFS=$(echo -en "\n\b")
+				for line in $list ;
+				do
+					7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=64m -ms=on -mhe=on -p$passtoken $line.7z $line
+				done
+				IFS=$SAVEIFS
+
+				result="
+				\n♹ Created the following archive(s) encrypted: \n
+				\n STATUS	FILENAME
+				$(
+				echo \\n
+				for d in $list; do
+				[[ -e $d.7z ]] && echo "Confirmed	:  $d.z7 \\n" || echo " Failed!	:  $d.z7 \\n"
+				done
+				)
+				\n Please review the above: ⏫"
+				display_result "Done creating encrypted archives"
+			;;
+			1) echo "Request cancelled" ; exit 1;;
+			255) echo "[esc] Request aborted" ; exit 255;;
+			* )  exit 1 ;;
+		esac
+	else
+		SAVEIFS=$IFS
+		IFS=$(echo -en "\n\b")
+		echo "☕ Please be patient, Large sets of files may take serious time..."
+
+		for line in $@ ;
+		do
+		7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=64m -ms=on -mhe=on $line.7z $line
+		done
+
+
+		IFS=$SAVEIFS
+		result="
+		Created the following archive(s): \n
+		\n STATUS	FILENAME
+		$(
+		echo \\n
+		for d in $@; do
+		[[ -e $d.7z ]] && echo "Confirmed	:  $d.z7 \\n" || echo " Failed!	:  $d.z7 \\n"
+		done
+		)
+		\n Please review the above: ⏫"
+		display_result "Done creating encrypted archives"
+	fi
+}
+
+
 
 
 
@@ -7174,6 +7335,11 @@ set_colors ()
 	chess="♟️ ♔ ♕ ♖ ♗ ♘ ♙ ♚ ♛ ♜ ♝ ♞ ♟"
 	colorcircle="🔴 🟠 🟡 🟢 🔵 🟣 🟤"
 	colorsquares=" 🟥 🟧 🟨 🟩 🟦 🟪 🟫"
+	#⏰ 	⏱ 	⏲ 	⏳ 	⏴ 	⏵ 	⏶ 	⏷ 	⏸ 	⏹ 	⏺
+	#⏩ 	⏪ 	⏫ 	⏬ 	⏭ 	⏮ 	⏯
+	# ☔ 	☕ 	☖ 	☗ 	☘ 	☙ 	☚ 	☛ 	☜ 	☝ 	☞ 	☟
+	# ♰ 	♱ 	♲ 	♳ 	♴ 	♵ 	♶ 	♷ 	♸ 	♹ 	♺ 	♻ 	♼ 	♽ 	♾ 	♿
+	# ⚐ 	⚑ 	⚒ 	⚓ 	⚔ 	⚕ 	⚖ 	⚗ 	⚘ 	⚙ 	⚚ 	⚛ 	⚜ 	⚝ 	⚞ 	⚟
 }
 
 
@@ -7196,7 +7362,8 @@ display_result ()
 #
 # End of Documentation
 
-	$RTD_GUI --backtitle "$BRANDING" --title "$1" --msgbox "$result" $HEIGHT $WIDTH
+	${RTD_GUI:-dialog} --backtitle "$BRANDING" --colors --no-collapse --title "$1" --msgbox "$result" ${HEIGHT:-"20"} ${WIDTH:-"80"}
+	clear
 }
 
 
