tweaks

diff --git a/System_Admin/rtd-join-avi b/System_Admin/rtd-join-avi
--- a/System_Admin/rtd-join-avi
+++ b/System_Admin/rtd-join-avi
@@ -1,3 +1,99 @@
 #!/bin/bash
+#
+#::             			A D M I N   C O M M A N D L E T   
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::// Simple bootable CD/DVD creation Tool //:::::::::::::::::::::// Linux //::::::::
+#::
+#:: Author:   	SLS  
+#:: Version 	1.00
+#::
+#::
+#::	Purpose: The purpose of the script is to write an ISO file to an optical device verbatim. 
+#::		  
+#::		 
+#::     Usage:	Simply execute this commandlet passing the parameter indicating where the ISO is located 
+#:: 		to accomplish this task. 
+#::     	
+#::     	Example: 
+#::		rtd-burniso path/to/file.iso
+#::     	
+#::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#
+# Additional information: 
+#
+# An ISO image is a disk image of an optical disc. In other words, it is an archive file that contains everything that would 
+# be written to an optical disc, sector by sector, including the optical disc file system.[1] ISO image files bear the .iso 
+# filename extension. The name ISO is taken from the ISO 9660 file system used with CD-ROM media, but what is known as an 
+# ISO image might also contain a UDF (ISO/IEC 13346) file system (commonly used by DVDs and Blu-ray Discs).
+#
+# ISO images can be created from optical discs by disk imaging software, or from a collection of files by optical disc authoring 
+# software, or from a different disk image file by means of conversion. Software distributed on bootable discs is often available 
+# for download in ISO image format. And like any other ISO image, it may be written to an optical disc such as CD or DVD. 
+#
+# This  script was originally developed for RuntimeData, a small OEM in Buffalo Center, IA.
+# This OEM and store nolonger exists as its owner has passed away.
+# This script is shared in the hopes that someone will find it useful.
+#
+# This script is intended to live in the ~/bin/ or /bin/ folder, alternatively in the $PATH.
+#
 
 
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Settings                 ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+
+# Set colors for prompting on screen.
+	YELLOW="\033[1;33m"
+	RED="\033[0;31m"
+	ENDCOLOR="\033[0m"
+	GREEN="\033[0;32m"
+	BLUE="\033[0;34m"
+
+
+if [ -f ~/bin/_rtd_functions ]; then 
+	source ~/bin/_rtd_functions
+else 
+	if -f [ /opt/rtd/scripts/_rtd_functions ]; then 
+		source /opt/rtd/scripts/_rtd_functions
+	else 
+		echo "RTD Functions not found... "
+		echo "Trying to retrieve them..."
+		wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_functions 
+		source ./_rtd_functions
+	fi
+fi
+
+
+
+if [[ "$RTDFUCTIONS" = "1" ]]
+      then
+        echo -e $GREEN "RTD functions loaded!" $ENDCOLOR
+      else
+        echo -e $RED "RTD functions NOT loaded!" $ENDCOLOR
+        echo -e $YELLOW " " $ENDCOLOR
+        echo -e $YELLOW "Cannit ensure that the correct software is available" $ENDCOLOR
+        echo -e $YELLOW "Quiting rather than cause potential damage..." $ENDCOLOR
+        exit 1
+fi
+
+
+###########################################################################
+##                                                                       ##
+##                       Script Executive                                ##
+##                                                                       ##
+###########################################################################
+check_dependencies mencoder
+check_dependencies dialog
+
+
+rtd_join_avis () {
+        mencoder -oac copy -ovc copy *.avi -o WHOLE-THING.avi
+}
+
+
+dialog --buildlist --title "AVI Joiner" 
+ 
diff --git a/System_Setup/_rtd_functions b/System_Setup/_rtd_functions
--- a/System_Setup/_rtd_functions
+++ b/System_Setup/_rtd_functions
@@ -247,6 +247,37 @@ SofwareManagmentAvailabilityCHK ()
 
 
 
+# Function to reset temporary configurations to their original setings from the 
+# distributor. To configure and/or automatically install Linux systems RTD OEM 
+# load process must make some changes to the system in question that are not 
+# good security practice or that may be disruptive during normal operations. 
+# These setings are not limited to bu include "auto login", "auto sudo" and 
+# "auto running scripts"... 
+rtd_oem_reset_default_environment_config () {
+
+	# Disable the automatically trying to install OEM software
+	mv /etc/xdg/autostart/org.runtimedata.oem.cofig.desktop /opt/rtd/scripts
+
+
+}
+
+
+
+# Function that, when called, will wait for an active internet connection 
+# to be available before before continuing. Most softwrare install activities 
+# need an active internet connection to be able to install and update software. 
+# Naturally, some in house loads use local mirrors, but if you can see the 
+# internet, you would have access to your own ropositories as well... 
+rtd_wait_for_internet_availability () {
+	echo "Waiting for internet access..."
+	echo "NOTE: Free access to the internet is required to continue."
+	while ! ping -c 1 -W 1 8.8.8.8; do
+		Waiting...
+		sleep 5
+	done
+}
+
+
 
 
 # Function to simplify updating system completely. At present this function sets the 
