Script simplifications...
Removed custom code and used shared code instead.

diff --git a/System_Admin/rtd-burniso b/System_Admin/rtd-burniso
--- a/System_Admin/rtd-burniso
+++ b/System_Admin/rtd-burniso
@@ -38,23 +38,28 @@
 #
 # This script is intended to live in the ~/bin/ or /bin/ folder, alternatively in the $PATH.
 #
-###########################################################################
-##                                                                       ##
-##                         Script  settings                              ##
-##                                                                       ##
-###########################################################################
-# Set library path if not defined:
-rtd_library=${rtd_library:-"/opt/rtd/scripts/_rtd_library"}
-if [[ -f ${rtd_library} ]]; then
-        source ${rtd_library}
-elif [[ ! -f ${rtd_library} ]]; then
-        echo "RTD Functions not found... "
-        echo "Trying to retrieve them..."
-        wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
-        source ./_rtd_library
-else
-        exit 1
-fi
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Functions                ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+
+check_rtd_library ()
+{
+        # Set library path if not defined:
+        rtd_library=${rtd_library:-"/opt/rtd/scripts/_rtd_library"}
+
+        if [[ -f ${rtd_library} ]]; then
+                source ${rtd_library}
+        elif [[ ! -f ${rtd_library} ]]; then
+                echo "RTD Functions not found... "
+                echo "Trying to retrieve them..."
+                wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
+                source ./_rtd_library
+        else
+                exit 1
+        fi
+}
 
 ###########################################################################
 ##                                                                       ##
@@ -62,19 +67,26 @@ fi
 ##                                                                       ##
 ###########################################################################
 
+# Ensure access to the rtd library functions:
+check_rtd_library
+
+# Check syntax this script is called with:
 if [[ -z "$1" ]]; then
-        echo "You must provide atleast one argument!
+        write_error "You must provide atleast one argument!
         Example: $0 ~/my_videos.iso"
         exit 1
 fi
 
+# Check that the indicated iso file exists:
 if [[ ! -f "$1" ]]; then
-        echo "The file $1 dies not exist or is not readable!"
+        write_error "The file $1 dies not exist or is not readable!"
         exit 1
 fi
 
+# Ensure that "cdrecord" is available on the system:
 check_dependencies cdrecord
 
+# Write iso to device:
 $IN = $ARGV[0];
 print "Writing the ISO file $IN to the cd... \n";
 print 'dd if=$IN | cdrecord -speed=16 dev=0,0,0 -eject -data -'
diff --git a/System_Admin/rtd-clear_iptables b/System_Admin/rtd-clear_iptables
--- a/System_Admin/rtd-clear_iptables
+++ b/System_Admin/rtd-clear_iptables
@@ -28,41 +28,40 @@
 #
 # This script is intended to live in the ~/bin/ or /bin/ folder, alternatively in the $PATH.
 
-###########################################################################
-##                                                                       ##
-##                       Commandlet settings                             ##
-##                                                                       ##
-###########################################################################
 
-# Elevate the privileges to root equivalent (if not already) to manage system...
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Functions                ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
-if [ ! "$UID" -eq 0 ]; then
-        if hash dialog 2>/dev/null ; then
-                # find  a diferent way... tempfile not universal...
-                data=$(tempfile 2>/dev/null)
-                trap "rm -f $data" 0 1 2 5 15
-                dialog --title "${Title}" --backtitle "${BackTitle}" --insecure --passwordbox "\n This functionality requires elevated priviledges. \n Please provide your (sudo) password" 10 90 2> $data
-                ret=$? ; clear
-                case $ret in
-                        0) cat $data | sudo -S bash "$0" "$*" ;;
-                        1) echo "Request cancelled" ;;
-                        255) [ -s $data ] && rm $data &>/dev/null || echo "[esc] Request aborted" ;;
-                        * ) rm $data &>/dev/null ; exit 1
-                esac
-                rm $data &>/dev/null
-                exit
+check_rtd_library ()
+{
+        # Set library path if not defined:
+        rtd_library=${rtd_library:-"/opt/rtd/scripts/_rtd_library"}
+
+        if [[ -f ${rtd_library} ]]; then
+                source ${rtd_library}
+        elif [[ ! -f ${rtd_library} ]]; then
+                echo "RTD Functions not found... "
+                echo "Trying to retrieve them..."
+                wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
+                source ./_rtd_library
         else
-                [ "$UID" -eq 0 ] || echo "This script needs administrative access..."
-                [ "$UID" -eq 0 ] || exec sudo -H bash "$0" "$@"
+                exit 1
         fi
-fi
+}
 
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Executive                ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
-###########################################################################
-##                                                                       ##
-##                         Execute                                       ##
-##                                                                       ##
-###########################################################################
+# Ensure access to the rtd library functions:
+check_rtd_library
+# Esure elevated privs:
+ensure_admin
 
 
 
diff --git a/System_Admin/rtd-ppa-checker b/System_Admin/rtd-ppa-checker
--- a/System_Admin/rtd-ppa-checker
+++ b/System_Admin/rtd-ppa-checker
@@ -21,17 +21,35 @@
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #
 #
-rtd_library=${rtd_library:-"/opt/rtd/scripts/_rtd_library"}
-if [[ -f ${rtd_library} ]]; then
-        source ${rtd_library}
-elif [[ ! -f ${rtd_library} ]]; then
-        echo "RTD Functions not found... "
-        echo "Trying to retrieve them..."
-        wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
-        source ./_rtd_library
-else
-        exit 1
-fi
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Functions                ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+
+check_rtd_library ()
+{
+        # Set library path if not defined:
+        rtd_library=${rtd_library:-"/opt/rtd/scripts/_rtd_library"}
+
+        if [[ -f ${rtd_library} ]]; then
+                source ${rtd_library}
+        elif [[ ! -f ${rtd_library} ]]; then
+                echo "RTD Functions not found... "
+                echo "Trying to retrieve them..."
+                wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
+                source ./_rtd_library
+        else
+                exit 1
+        fi
+}
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Executive                ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+
+check_rtd_library
 
 ensure_admin
 rtd_ppa_checker
