Detect issue on BTRFS file system for swap file creation

diff --git a/System_Admin/rtd-make-swap b/System_Admin/rtd-make-swap
--- a/System_Admin/rtd-make-swap
+++ b/System_Admin/rtd-make-swap
@@ -29,28 +29,39 @@
 # This script is intended to live in the ~/bin/ or /bin/ folder, alternatively in the $PATH.
 
 
-[ "$UID" -eq 0 ] || echo "This script needs administrative access..." 
-[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
+
+
 ###########################################################################
 ##                                                                       ##
 ##                       Set Environment                                 ##
+##                                                                       ##
+###########################################################################
+source /opt/rtd/scripts/_rtd_library
+ensure_admin 
+
+###########################################################################
+##                                                                       ##
+##                       EXECUTIVE                                       ##
 ##                                                                       ##
 ###########################################################################
 
 
 # Do argument checks
 if [ ! "$#" -ge 1 ]; then
-    echo "Usage: $0 {size}"
-    echo "Example: $0 4G"
-    echo "(Default path: /swapfile)"
-    echo "Optional path: Usage: $0 {size} {path}"
-    exit 1
+	echo "Usage: $0 {size}"
+	echo "Example: $0 4G"
+	echo "(Default path: /swapfile)"
+	echo "Optional path: Usage: $0 {size} {path}"
+	exit 1
 fi
 
-if [ mount |grep "/ " |grep btrfs ]; then
-    echo "$RED ERROR: swapfiles cannot be allocated on BTRFS. Please use an ext4 or xfs partition"
-    exit 1
+if mount |grep "/ " |grep btrfs; then
+	echo "$RED ERROR: swapfiles cannot be allocated on BTRFS. Please use an ext4 or xfs partition $ENDCOLOR"
+	exit 1
 fi
+
+
+
 
 ## Intro
 echo "Welcome to Swap setup script! This script will automatically setup a swap file and enable it."
@@ -64,19 +75,23 @@ SWAP_SIZE=$1
 # Get path from second argument (default to /swapfile)
 SWAP_PATH="/swapfile"
 if [ ! -z "$2" ]; then
-    SWAP_PATH=$2
+	SWAP_PATH=$2
 fi
 
+if -e $SWAP_PATH ; then
+	echo "$RED ERROR: the file $SWAP_PATH already exists! Please chose a different name."
+	exit 1
+fi
 
 ## Run
-sudo fallocate -l $SWAP_SIZE $SWAP_PATH  # Allocate size
-sudo chmod 600 $SWAP_PATH                # Make it non-world readable (bad!)
-sudo mkswap $SWAP_PATH                   # Setup swap"
-sudo swapon $SWAP_PATH                   # Enable swap
+sudo fallocate -l "$SWAP_SIZE" "$SWAP_PATH"  # Allocate size
+sudo chmod 600 "$SWAP_PATH"                # Make it non-world readable (bad!)
+sudo mkswap "$SWAP_PATH"                   # Setup swap"
+sudo swapon "$SWAP_PATH"                   # Enable swap
 echo "$SWAP_PATH   none    swap    sw    0   0" | sudo tee /etc/fstab -a # Add to fstab
 
 ## Outro
 
 echo
-echo "Done! You now have a $SWAP_SIZE swap file at $SWAP_PATH"
+echo "$GREEN Done! You now have a $SWAP_SIZE swap file at $SWAP_PATH $ENDCOLOR"
 
