Minot updates

diff --git a/System_Admin/rtd-make-swap b/System_Admin/rtd-make-swap
--- a/System_Admin/rtd-make-swap
+++ b/System_Admin/rtd-make-swap
@@ -73,25 +73,24 @@ echo
 SWAP_SIZE=$1
 
 # Get path from second argument (default to /swapfile)
-SWAP_PATH="/swapfile"
+SWAP_PATH="/swapfile-$RANDOM"
 if [ ! -z "$2" ]; then
 	SWAP_PATH=$2
+	if -e $SWAP_PATH ; then
+		echo -e "$RED ERROR: the file $SWAP_PATH already exists! Please chose a different name."
+		exit 1
+	fi
 fi
 
-if -e $SWAP_PATH ; then
-	echo "$RED ERROR: the file $SWAP_PATH already exists! Please chose a different name."
-	exit 1
-fi
 
-## Run
+
 sudo fallocate -l "$SWAP_SIZE" "$SWAP_PATH"  # Allocate size
 sudo chmod 600 "$SWAP_PATH"                # Make it non-world readable (bad!)
 sudo mkswap "$SWAP_PATH"                   # Setup swap"
 sudo swapon "$SWAP_PATH"                   # Enable swap
 echo "$SWAP_PATH   none    swap    sw    0   0" | sudo tee /etc/fstab -a # Add to fstab
 
-## Outro
 
 echo
-echo "$GREEN Done! You now have a $SWAP_SIZE swap file at $SWAP_PATH $ENDCOLOR"
+echo -e "$GREEN Done! You now have a $SWAP_SIZE swap file at $SWAP_PATH $ENDCOLOR"
 
