Fixed to handle *.xxx

diff --git a/System_Admin/rtd-7z-this b/System_Admin/rtd-7z-this
--- a/System_Admin/rtd-7z-this
+++ b/System_Admin/rtd-7z-this
@@ -53,16 +53,10 @@
 ###########################################################################
 #
 # Set colors for prompting on screen.
-YELLOW="\033[1;33m"
-RED="\033[0;31m"
-ENDCOLOR="\033[0m"
 
-# Ask for encryption phrase and store it temporarily.
-clear
-echo  Hello $USER ... I am going to compress $*
-echo  To cancel this, just close the terminal or press "CRTL C".
-echo
-read -p "Press the [ENTER] key to continue..."
+DIR="$*"
+source /opt/rtd/scripts/_rtd_library
+ 
 
 
 ###########################################################################
@@ -75,12 +69,59 @@ read -p "Press the [ENTER] key to continue..."
 # And remember to handle or replace white spaces with underscore so the shell commands
 # don't fail. Here IFS is altered to not consider a whitespace as a separator.
 
-SAVEIFS=$IFS
-IFS=$(echo -en "\n\b")
-  for line in $( echo $* )
-   do
-    7z a -t7z -m0=lzma2 -mx=9 -myx=9 -mfb=64 -md=64m -ms=on -mhe=on $line.7z $line
-   done
-   IFS=$SAVEIFS
-echo "Created the following archive(s) un-encrypted:"
-ls *.7z
+[ "$DIR" == "" ] && echo usage...
+ 
+OLDIFS=$IFS
+IFS=$'\n'
+fileArray=($(ls -I $*))
+IFS=$OLDIFS
+tLen=${#fileArray[@]}
+
+clear
+echo -e "$colorcircle"
+echo -e  "Hello $YELLOW $USER $ENDCOLOR ... I am going to compress $YELLOW $tLen $ENDCOLOR files: "
+for (( i=0; i<${tLen}; i++ ));
+do
+	echo -e $GREEN "${fileArray[$i]}	$ENDCOLOR"
+done
+
+echo  "To cancel this, just close the terminal or press "CRTL C"."
+echo " "
+read -p "Press the [ENTER] key to continue..."
+
+echo -e "☕ Please be patient as lots of data may take time to compress..."
+for (( i=0; i<${tLen}; i++ ));
+do
+  7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=64m -ms=on -mhe=on "${fileArray[$i]}".7z "${fileArray[$i]}"
+done
+
+echo "Created the following archive(s) UN-encrypted:"
+echo " FILENAME         STATUS"
+for (( i=0; i<${tLen}; i++ )); do 
+        [[ -e "${fileArray[$i]}".7z ]] && echo -e "$GREEN Confirmed     $ENDCOLOR: $YELLOW "${fileArray[$i]}".7z $ENDCOLOR" || echo -e "$RED Failed!    $ENDCOLOR: $YELLOW "${fileArray[$i]}".7z $ENDCOLOR"
+done
+echo "Please review the output above to review all the progress ⏫"
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
