Minor edits.

diff --git a/System_Admin/rtd-7z-encrypt-this b/System_Admin/rtd-7z-encrypt-this
--- a/System_Admin/rtd-7z-encrypt-this
+++ b/System_Admin/rtd-7z-encrypt-this
@@ -46,7 +46,6 @@
 # or go to: https://www.mankier.com/1/7z#
 
 
-
 ###########################################################################
 ##                                                                       ##
 ##                       Set Environment                                 ##
@@ -54,21 +53,24 @@
 ###########################################################################
 #
 # Set colors for prompting on screen.
-YELLOW="\033[1;33m"
-RED="\033[0;31m"
-ENDCOLOR="\033[0m"
+source /opt/rtd/scripts/_rtd_library
 
 # Ask for encryption phrase and store it temporarily.
 clear
-echo  Hello $USER ... I am going to compress each file or folder that
-echo  I find in this folder. These are:
-echo
-ls -I "*.7z" --color=always
-echo
-echo  To cancel this, just close the terminal or press "CRTL C".
-echo
+echo -e "
+Hello $YELLOW $USER $ENDCOLOR ... I am going to compress $GREEN $@ $ENDCOLOR
+To cancel this, just close the terminal or press "CRTL C".
+"
 read -p "Press the [ENTER] key to continue..."
+echo "
 
+To encrypt the content you have to give me a phrase to encrypt it with.
+This can be anything in one long word, but never forget it!
+"
+
+echo -e $YELLOW
+read -sp 'Enter encryption phrase: ' passtoken
+echo -e $ENDCOLOR
 
 ###########################################################################
 ##                                                                       ##
@@ -80,12 +82,18 @@ read -p "Press the [ENTER] key to continue..."
 # And remember to handle or replace white spaces with underscore so the shell commands
 # don't fail. Here IFS is altered to not consider a whitespace as a separator.
 
-SAVEIFS=$IFS
-IFS=$(echo -en "\n\b")
-  for line in $(ls -I "*.7z")
+echo "☕ Please be patient, Large sets of files may take serious time..."
+
+  for line in $( echo $* )
    do
-    7z a -t7z -m0=lzma2 -mx=9 -myx=9 -mfb=64 -md=64m -ms=on -mhe=on -v24m $line.7z $line
+    7z a -t7z -m0=lzma2 -mx=9 -myx=9 -mfb=64 -md=64m -ms=on -mhe=on -p$passtoken $line.7z $line
    done
-   IFS=$SAVEIFS
-echo Created the following archives un-encrypted:
-ls *.7z
+
+echo "Created the following archive(s) encrypted:"
+echo " FILENAME		STATUS"
+for d in $( echo $@ ); do 
+	[[ -e $d.7z ]] && echo -e "$GREEN Confirmed	$ENDCOLOR: $YELLOW $d.z7 $ENDCOLOR" || echo -e "$RED Failed!	$ENDCOLOR: $YELLOW $d.z7 $ENDCOLOR"
+done
+echo "Please review the output above to review all the progress ⏫"
+
+
