Some optimization of code.

diff --git a/System_Admin/rtd-make-swap b/System_Admin/rtd-make-swap
--- a/System_Admin/rtd-make-swap
+++ b/System_Admin/rtd-make-swap
@@ -39,59 +39,60 @@
 source /opt/rtd/scripts/_rtd_library
 ensure_admin
 #clear
+SWAP_SIZE=$1
+SWAP_PATH=$2
+: "${SWAP_SIZE:=4G}"
+: "${SWAP_PATH:="/swapfile-$RANDOM"}"
 
 ###########################################################################
 ##                                                                       ##
 ##                       EXECUTIVE                                       ##
 ##                                                                       ##
 ###########################################################################
-
-
-# Do argument checks
-if [ ! "$#" -ge 1 ]; then
+usage_mesage () {
 	echo "Usage: $0 {size}"
 	echo "Example: $0 4G"
 	echo "(Default path: /swapfile)"
 	echo "Optional path: Usage: $0 {size} {path}"
+}
+
+
+if [[ -z $SWAP_SIZE ]]; then
+	# Fail if we are not five any argument
+	echo -e $RED "Please tell me what size swap file to make!" $ENDCOLOR
+	usage_mesage
 	exit 1
-fi
-
-
-## Intro
-echo -e $BLUE"Welcome to Swap setup script! This script will automatically setup a swap file and enable it."$ENDCOLOR
-echo
-
-## Setup variables
-
-# Get size from first argument
-SWAP_SIZE=$1
-
-# Get path from second argument (default to /swapfile)
-SWAP_PATH="/swapfile-$RANDOM"
-if [ ! -z "$2" ]; then
-	SWAP_PATH=$2
-	if -e $SWAP_PATH ; then
-		echo -e "$RED ERROR: the file $SWAP_PATH already exists! Please chose a different name."
+elif [[ ! "${SWAP_SIZE:0:1}" -ge "1" ]]; then
+	# Fail if the argument is not a numer
+	echo -e $RED "The size for swap file must be a number!" $ENDCOLOR
+	usage_mesage
+	exit 1
+else
+	if [[ -e $SWAP_PATH ]]; then
+		echo -e "$RED ERROR: the file $SWAP_PATH already exists! Please choose a different name."
 		exit 1
 	fi
+	echo -e $BLUE"Welcome to Swap setup script! This script will automatically setup a swap file and enable it."$ENDCOLOR
+	echo
 
-	sudo fallocate -l "$SWAP_SIZE" "$SWAP_PATH"	|| echo -e $RED Error creting actual swapfile using fallocate!$ENDCOLOR ; exit 1
-	sudo chmod 600 "$SWAP_PATH"			|| echo -e $RED Error changing premissions$ENDCOLOR ; exit 1
-	sudo mkswap "$SWAP_PATH"			|| echo -e $RED Error formating $SWAP_PATH as a swapspace!$ENDCOLOR ; exit 1
-
-	if sudo swapon "$SWAP_PATH" ; then
+	fallocate -l "$SWAP_SIZE" "$SWAP_PATH"	&& echo "Allocated $SWAP_SIZE swap file: $SWAP_PATH" || (echo -e $RED Error creting actual swapfile using fallocate!$ENDCOLOR ; exit 1)
+	chmod 600 "$SWAP_PATH"			&& echo "Sucessfully modified permissions on $SWAP_PATH" || (echo -e $RED Error changing premissions$ENDCOLOR ; exit 1)
+	mkswap "$SWAP_PATH"			&& (echo "Sucessfully formatted $SWAP_PATH as a swap partition" ; file -s $SWAP_PATH) || (echo -e $RED Error formating $SWAP_PATH as a swapspace!$ENDCOLOR ; exit 1)
+	swapon "$SWAP_PATH" 			# Turn on the swap file...
+	if [ $? = 0 ]; then
 		echo "$SWAP_PATH   none    swap    sw    0   0" | sudo tee /etc/fstab -a # Add to fstab
-		echo
 		echo -e "$GREEN Done! You now have a $SWAP_SIZE swap file at $SWAP_PATH $ENDCOLOR"
 	else 
 		if df -T $SWAP_PATH |grep btrfs >/dev/null ; then
 			echo -e "$RED ERROR: swapfiles cannot be allocated on BTRFS. \n The root filesystem is BTRFS. Please use an ext4 or xfs partition. 
 			This is a BUG and hopefully it will be fixed soon... $ENDCOLOR"
 			exit 1
+		else 
+			echo $RED "An unknown error occurred with starting the swap partition.." $ENDCOLOR
+			exit 1
 		fi
 	fi
+
 fi
-
-
 
 
